import type { SdkCandidate } from "../../../shared/contracts/android";
import { ONBOARDING_LABELS } from "../labels";

export const ANDROID_LABELS = {
  hero: {
    title: ONBOARDING_LABELS.titles.android,
    description:
      "Run Android builds from the sandbox on an emulator on this computer, like Android Studio's device manager. Downloads about 2.5 GB.",
  },
  accel: {
    title: "Hardware acceleration",
    description: "The emulator needs the CPU's virtualization extensions to run at a usable speed.",
    refresh: "Check again",
    checking: "Checking acceleration…",
    openDocs: "Learn more",
  },
  sdk: {
    title: "SDK location",
    description: "Reuse an Android SDK that already has the emulator, or install a new one for Tesseract.",
    installNew: "Install a new SDK for Tesseract",
    sources: {
      TESSERACT_ANDROID_SDK_ROOT: "TESSERACT_ANDROID_SDK_ROOT",
      ANDROID_SDK_ROOT: "ANDROID_SDK_ROOT",
      ANDROID_HOME: "ANDROID_HOME",
      "studio-default": "Android Studio SDK",
      "tesseract-default": "Tesseract SDK",
    } satisfies Record<SdkCandidate["source"], string>,
    candidate: (path: string, emulator: string | null, images: number) =>
      [path, emulator ? `emulator ${emulator}` : "no emulator", `${images} system ${images === 1 ? "image" : "images"}`].join(" · "),
  },
  packages: {
    title: "SDK packages",
    description: "Pick the system images to download. The emulator and platform tools are always included.",
    columns: { name: "Name", api: "API", abi: "ABI", variant: "Variant", size: "Size", status: "Status" },
    tools: "SDK tools",
    images: "System images",
    emulator: "Android Emulator",
    platformTools: "Platform tools",
    googleApis: "Google APIs",
    showAll: (count: number) => `Show all ${count}`,
    showLess: "Show fewer",
    selectAll: "Select every system image",
    select: (name: string) => `Install ${name}`,
    status: { installed: "Installed", update: "Update", missing: "Not installed" },
    loading: "Loading Google's package list…",
    loadError: (error: string) => `Couldn't load Google's package list: ${error}`,
    retry: "Retry",
    none: "Google publishes no Google APIs system image for this computer's CPU.",
    alwaysIncluded: "Always included",
    needsEmulator: (min: string) => `This system image needs emulator ${min} or newer`,
  },
  versions: {
    30: "11",
    31: "12",
    32: "12L",
    33: "13",
    34: "14",
    35: "15",
    36: "16",
  } as Record<number, string>,
  imageName: (api: number, version: string | null) => (version ? `Android ${version}` : `API ${api}`),
  imageTitle: (api: number, version: string | null) => (version ? `Android ${version} (API ${api})` : `API ${api}`),
  avd: {
    title: "Virtual device",
    description: "Tesseract writes the device files itself, like Android Studio's device manager.",
    name: "Name",
    nameHint: "Letters, digits, dots, dashes and underscores",
    nameInvalid: "Use only letters, digits, dots, dashes and underscores",
    nameEmpty: "Enter a name",
    nameTaken: (name: string) => `An AVD named ${name} already exists`,
    image: "System image",
    imageNone: "Select a system image above",
    device: "Device profile",
    memory: "Memory",
    cores: "CPU cores",
    storage: "Internal storage",
    units: { mb: "MB", cores: "cores", gb: "GB" },
    decrease: (title: string) => `Decrease ${title.toLowerCase()}`,
    increase: (title: string) => `Increase ${title.toLowerCase()}`,
    existing: (count: number) => `${count} existing virtual ${count === 1 ? "device" : "devices"} in this SDK`,
  },
  summary: {
    title: "Download",
    total: "Total",
    totalValue: (download: string, disk: string) => `${download} download · about ${disk} on disk`,
    nothing: "Everything is already installed",
    lowSpace: (free: string, dir: string) => `Only ${free} free in ${dir}`,
  },
  licenses: {
    title: "Licenses",
    intro: "Read and accept each license to download the selected packages.",
    accept: "I accept the terms of this license",
    acceptAndInstall: "Accept and install",
    cancel: "Cancel",
    names: {
      "android-sdk-license": "Android SDK License",
      "android-sdk-preview-license": "Android SDK Preview License",
      "android-sdk-arm-dbt-license": "Android SDK ARM DBT License",
    } as Record<string, string>,
    accepted: "Accepted",
    pending: "Not accepted",
    missingText: "The license text isn't in Google's package list.",
  },
  queue: {
    title: "Downloads",
    description: "Tesseract downloads, verifies and unpacks each package into the SDK.",
    waiting: "Waiting",
    installed: "Installed",
    verifying: "Verifying…",
    extracting: (received: number, total: number) => (total > 0 ? `Extracting… ${received}/${total}` : "Extracting…"),
    transfer: (received: string, total: string, rate: string | null) => (rate ? `${received} of ${total} · ${rate}` : `${received} of ${total}`),
    accel: "Hardware acceleration",
    accelDetail: "Running emulator -accel-check",
    avd: (name: string) => `Virtual device ${name}`,
    avdDetail: "Writing the device files",
  },
  done: {
    ready: (avd: string, version: string, abi: string) => `${avd} is ready · Android ${version} · ${abi}`,
    sdk: "SDK",
    emulator: "Emulator",
    avd: "AVD",
    noIsolation: (os: string) =>
      `On ${os} the emulator runs without network isolation, so Tesseract won't connect it to the sandbox automatically. You can still run it on this computer.`,
    osNames: { darwin: "macOS", win32: "Windows", linux: "Linux" } as Record<string, string>,
    warningsTitle: "Finished with warnings",
  },
  failed: "The Android setup failed",
  cancelled: "The download was cancelled. Install resumes where it stopped.",
  unsupportedTitle: "This computer can't run the Android emulator",
  buttons: {
    back: ONBOARDING_LABELS.buttons.back,
    skip: ONBOARDING_LABELS.buttons.skip,
    cancel: ONBOARDING_LABELS.buttons.cancel,
    retry: ONBOARDING_LABELS.buttons.retry,
    continue: ONBOARDING_LABELS.buttons.continue,
    install: "Install",
    use: (avd: string) => `Use ${avd}`,
  },
} as const;
