import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { appendFileSync, mkdirSync, utimesSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  ClaudeSessionListSchema,
  UsageReportSchema,
  type AgentRun,
  type ClaudeSession,
  type TerminalInfo,
  type UsageReport,
} from "@tesseract/protocol";
import { loadConfig } from "../src/config";
import { listTranscripts, refreshTranscript, type TranscriptFile } from "../src/services/transcripts";
import { UsageService, type SessionSources } from "../src/services/usage";
import { makeTempDir, removeTempDirs, startTestController, TEST_TOKEN, type TestController } from "./helpers";

const NOW = Date.parse("2026-09-23T12:00:00.000Z");
const USAGE = { input_tokens: 10, output_tokens: 20, cache_creation_input_tokens: 30, cache_read_input_tokens: 40 };

type Line = Record<string, unknown>;

const user = (content: unknown, extra: Line = {}): Line => ({
  type: "user",
  timestamp: "2026-09-23T10:00:00.000Z",
  message: { role: "user", content },
  ...extra,
});

const assistant = (id: string, text: string, extra: { model?: string; timestamp?: string; requestId?: string; usage?: Line } = {}): Line => ({
  type: "assistant",
  timestamp: extra.timestamp ?? "2026-09-23T10:01:00.000Z",
  ...(extra.requestId ? { requestId: extra.requestId } : {}),
  message: {
    id,
    role: "assistant",
    model: extra.model ?? "claude-opus-4-5",
    usage: extra.usage ?? USAGE,
    content: [{ type: "text", text }],
  },
});

const jsonl = (lines: Line[], cwd: string, sessionId: string) =>
  lines.map((line) => JSON.stringify({ sessionId, cwd, ...line })).join("\n") + "\n";

function writeTranscript(root: string, cwd: string, sessionId: string, lines: Line[], mtimeMs = NOW): string {
  const dir = join(root, "projects", cwd.replace(/[^A-Za-z0-9]/g, "-"));
  mkdirSync(dir, { recursive: true });
  const path = join(dir, `${sessionId}.jsonl`);
  writeFileSync(path, jsonl(lines, cwd, sessionId));
  utimesSync(path, mtimeMs / 1000, mtimeMs / 1000);
  return path;
}

async function fileAt(path: string, sessionId: string): Promise<TranscriptFile> {
  const stats = await Bun.file(path).stat();
  return { path, sessionId, subagent: false, size: stats.size, mtimeMs: stats.mtimeMs };
}

afterAll(() => {
  removeTempDirs();
});

describe("transcript parser", () => {
  const cwd = "/workspace/projects/site";

  test("dedupes content blocks of one message, skips synthetic messages and keeps the last assistant text", async () => {
    const root = makeTempDir("claude");
    const path = writeTranscript(root, cwd, "s1", [
      user("hello"),
      assistant("m1", "Let me look.", { requestId: "r1" }),
      assistant("m1", "Reading files", { requestId: "r1" }),
      assistant("m2", "All   done.\nBye", { requestId: "r2" }),
      assistant("m3", "Not logged in · Please run /login", { model: "<synthetic>", usage: { input_tokens: 999 } }),
      { type: "summary", summary: "ignored" },
    ]);
    appendFileSync(path, "{not json\n");
    const transcript = await refreshTranscript(undefined, await fileAt(path, "s1"));
    expect(transcript.records.size).toBe(2);
    expect(transcript.usage).toEqual({ inputTokens: 20, outputTokens: 40, cacheReadTokens: 80, cacheWriteTokens: 60, totalTokens: 200 });
    expect(transcript.model).toBe("claude-opus-4-5");
    expect(transcript.preview).toBe("All done. Bye");
    expect(transcript.cwd).toBe(cwd);
    expect(transcript.startedAt).toBe("2026-09-23T10:00:00.000Z");
    expect(transcript.lastActiveAt).toBe("2026-09-23T10:01:00.000Z");
  });

  test("the title is the first real prompt, one line, at most 120 characters", async () => {
    const root = makeTempDir("claude");
    const long = `Refactor   the\nlogin flow ${"x".repeat(200)}`;
    const path = writeTranscript(root, cwd, "s2", [
      user("Caveat: The messages below were generated by the user while running local commands.", { isMeta: true }),
      user("<command-name>/clear</command-name>\n<command-message>clear</command-message>"),
      user("<local-command-stdout></local-command-stdout>"),
      user([{ type: "tool_result", tool_use_id: "t1", content: "ok" }]),
      user("a sidechain prompt", { isSidechain: true }),
      user([
        { type: "text", text: "<system-reminder>be nice</system-reminder>" },
        { type: "text", text: long },
      ]),
      user("second prompt"),
    ]);
    const transcript = await refreshTranscript(undefined, await fileAt(path, "s2"));
    expect(transcript.title?.startsWith("Refactor the login flow xxx")).toBe(true);
    expect(transcript.title).toHaveLength(120);
    expect(transcript.title?.endsWith("…")).toBe(true);
    expect(transcript.preview).toBeNull();
  });

  test("reads only appended bytes and waits for a complete last line", async () => {
    const root = makeTempDir("claude");
    const path = writeTranscript(root, cwd, "s3", [user("first"), assistant("m1", "one")]);
    const first = await refreshTranscript(undefined, await fileAt(path, "s3"));
    const offset = first.offset;
    expect(offset).toBe(first.size);
    expect(await refreshTranscript(first, await fileAt(path, "s3"))).toBe(first);

    const next = JSON.stringify({ sessionId: "s3", cwd, ...assistant("m2", "two", { timestamp: "2026-09-23T11:00:00.000Z" }) });
    appendFileSync(path, next.slice(0, 40));
    const partial = await refreshTranscript(first, await fileAt(path, "s3"));
    expect(partial).toBe(first);
    expect(partial.offset).toBe(offset);
    expect(partial.records.size).toBe(1);

    appendFileSync(path, `${next.slice(40)}\n`);
    const grown = await refreshTranscript(partial, await fileAt(path, "s3"));
    expect(grown).toBe(first);
    expect(grown.records.size).toBe(2);
    expect(grown.preview).toBe("two");
    expect(grown.lastActiveAt).toBe("2026-09-23T11:00:00.000Z");
    expect(grown.title).toBe("first");

    writeFileSync(path, jsonl([user("rewritten")], cwd, "s3"));
    const rewritten = await refreshTranscript(grown, await fileAt(path, "s3"));
    expect(rewritten).not.toBe(first);
    expect(rewritten.title).toBe("rewritten");
    expect(rewritten.records.size).toBe(0);
  });

  test("lists session and subagent transcripts and tolerates a missing directory", async () => {
    expect(await listTranscripts("/nonexistent/claude/projects")).toEqual([]);
    const root = makeTempDir("claude");
    writeTranscript(root, cwd, "parent", [user("hi")]);
    const subagents = join(root, "projects", cwd.replace(/[^A-Za-z0-9]/g, "-"), "parent", "subagents");
    mkdirSync(subagents, { recursive: true });
    writeFileSync(join(subagents, "agent-1.jsonl"), jsonl([assistant("sub1", "sub")], cwd, "parent"));
    const files = await listTranscripts(join(root, "projects"));
    expect(files.map(({ sessionId, subagent }) => ({ sessionId, subagent })).sort((a, b) => Number(a.subagent) - Number(b.subagent))).toEqual([
      { sessionId: "parent", subagent: false },
      { sessionId: "parent", subagent: true },
    ]);
  });
});

describe("UsageService", () => {
  const workspace = "/workspace";
  const site = "/workspace/projects/site";
  const blog = "/workspace/projects/blog/app";
  const DAY = 86_400_000;

  const run = (overrides: Partial<AgentRun>): AgentRun => ({
    id: "run_aaaaaaaaaa",
    projectId: "site",
    prompt: "p",
    mode: null,
    attachments: [],
    sessionId: null,
    claudeAccountId: null,
    state: "succeeded",
    startedAt: "2026-09-23T09:00:00.000Z",
    endedAt: null,
    usage: null,
    result: null,
    error: null,
    archivedAt: null,
    ...overrides,
  });

  const terminal = (overrides: Partial<TerminalInfo>): TerminalInfo => ({
    id: "trm_aaaaaaaaaa",
    kind: "claude",
    projectId: "site",
    title: "Claude · site",
    cwd: site,
    pid: 4242,
    cols: 80,
    rows: 24,
    state: "running",
    exitCode: null,
    createdAt: "2026-09-23T09:30:00.000Z",
    ...overrides,
  });

  function setup(sources: Partial<SessionSources> = {}) {
    const root = makeTempDir("claude");
    const config = loadConfig({ TESSERACT_WORKSPACE: workspace, TESSERACT_TOKEN: TEST_TOKEN, CLAUDE_CONFIG_DIR: root });
    const service = new UsageService(config, { runs: () => [], terminals: () => [], ...sources }, () => NOW);
    return { root, service };
  }

  test("a missing Claude directory yields a zero-filled report and no sessions", async () => {
    const { service } = setup();
    const report = UsageReportSchema.parse(await service.usage({ days: 3 }));
    expect(report.from).toBe("2026-09-21T00:00:00.000Z");
    expect(report.to).toBe("2026-09-23T12:00:00.000Z");
    expect(report.daily.map((day) => day.date)).toEqual(["2026-09-21", "2026-09-22", "2026-09-23"]);
    expect(report.daily.every((day) => day.totalTokens === 0 && day.sessions === 0)).toBe(true);
    expect(report.totals).toMatchObject({ totalTokens: 0, messages: 0, sessions: 0 });
    expect(report.models).toEqual([]);
    expect(report.projects).toEqual([]);
    expect(await service.sessions()).toEqual([]);
    expect((await service.usage()).daily).toHaveLength(30);
  });

  test("aggregates days, models and projects inside the range", async () => {
    const { root, service } = setup();
    writeTranscript(root, site, "a", [
      user("site work"),
      assistant("a1", "x", { timestamp: "2026-09-22T10:00:00.000Z" }),
      assistant("a2", "y", { timestamp: "2026-09-23T10:00:00.000Z", model: "claude-haiku-4-5" }),
      assistant("old", "z", { timestamp: "2026-09-10T10:00:00.000Z" }),
    ]);
    writeTranscript(root, site, "a-resumed", [assistant("a2", "copied", { timestamp: "2026-09-23T10:00:00.000Z", model: "claude-haiku-4-5" })]);
    writeTranscript(root, blog, "b", [assistant("b1", "x", { usage: { ...USAGE, output_tokens: 1000 } })]);
    writeTranscript(root, "/tmp/elsewhere", "c", [assistant("c1", "x")]);
    writeTranscript(root, site, "stale", [assistant("s1", "x", { timestamp: "2026-09-23T10:00:00.000Z" })], NOW - 10 * DAY);

    const report = UsageReportSchema.parse(await service.usage({ days: 2 }));
    expect(report.days).toBe(2);
    expect(report.totals).toEqual({
      inputTokens: 40,
      outputTokens: 1060,
      cacheReadTokens: 160,
      cacheWriteTokens: 120,
      totalTokens: 1380,
      messages: 4,
      sessions: 3,
    });
    expect(report.daily.map(({ date, messages, sessions }) => ({ date, messages, sessions }))).toEqual([
      { date: "2026-09-22", messages: 1, sessions: 1 },
      { date: "2026-09-23", messages: 3, sessions: 3 },
    ]);
    expect(report.models.map(({ model, messages, totalTokens }) => ({ model, messages, totalTokens }))).toEqual([
      { model: "claude-opus-4-5", messages: 3, totalTokens: 1280 },
      { model: "claude-haiku-4-5", messages: 1, totalTokens: 100 },
    ]);
    expect(report.projects.map(({ projectId, messages, sessions, totalTokens }) => ({ projectId, messages, sessions, totalTokens }))).toEqual([
      { projectId: "blog", messages: 1, sessions: 1, totalTokens: 1080 },
      { projectId: "site", messages: 2, sessions: 1, totalTokens: 200 },
      { projectId: null, messages: 1, sessions: 1, totalTokens: 100 },
    ]);
  });

  test("lists sessions newest first, filters by project, limits and links runs and terminals", async () => {
    const runs = [
      run({ id: "run_old0000000", sessionId: "from-run", startedAt: "2026-09-20T08:00:00.000Z" }),
      run({ id: "run_new0000000", sessionId: "from-run", state: "running", startedAt: "2026-09-23T08:00:00.000Z" }),
    ];
    const terminals = [
      terminal({ id: "trm_bypid00000", pid: 4242, createdAt: "2026-09-23T09:00:00.000Z" }),
      terminal({ id: "trm_bycwd00000", pid: 5151, cwd: blog, projectId: "blog", createdAt: "2026-09-23T09:00:00.000Z" }),
      terminal({ id: "trm_exited0000", pid: 6161, state: "exited" }),
      terminal({ id: "trm_shell00000", kind: "shell", pid: 7171 }),
    ];
    const { root, service } = setup({ runs: () => runs, terminals: () => terminals });
    const at = (hour: number) => `2026-09-23T${String(hour).padStart(2, "0")}:00:00.000Z`;
    writeTranscript(root, site, "from-run", [user("run prompt", { timestamp: at(8) }), assistant("r1", "run answer", { timestamp: at(8) })]);
    writeTranscript(root, site, "from-pid", [user("pid prompt", { timestamp: at(9) }), assistant("p1", "pid answer", { timestamp: at(11) })]);
    writeTranscript(root, blog, "from-cwd", [user("cwd prompt", { timestamp: at(10) })], NOW);
    writeTranscript(root, blog, "older-blog", [user("old blog", { timestamp: "2026-09-22T10:00:00.000Z" })], NOW - DAY);
    writeTranscript(root, "/tmp/x", "plain", [user("plain", { timestamp: at(7) })], NOW - 5 * 3_600_000);
    mkdirSync(join(root, "sessions"), { recursive: true });
    writeFileSync(join(root, "sessions", "4242.json"), JSON.stringify({ pid: 4242, sessionId: "from-pid", cwd: site }));
    writeFileSync(join(root, "sessions", "5151.json"), JSON.stringify({ pid: 1, sessionId: "wrong-owner" }));

    const sessions = ClaudeSessionListSchema.parse(await service.sessions());
    const pick = (list: ClaudeSession[]) =>
      list.map(({ sessionId, projectId, source, agentRunId, terminalId, active }) => ({ sessionId, projectId, source, agentRunId, terminalId, active }));
    expect(pick(sessions)).toEqual([
      { sessionId: "from-pid", projectId: "site", source: "terminal", agentRunId: null, terminalId: "trm_bypid00000", active: true },
      { sessionId: "from-cwd", projectId: "blog", source: "terminal", agentRunId: null, terminalId: "trm_bycwd00000", active: true },
      { sessionId: "from-run", projectId: "site", source: "agent-run", agentRunId: "run_new0000000", terminalId: null, active: true },
      { sessionId: "plain", projectId: null, source: "cli", agentRunId: null, terminalId: null, active: false },
      { sessionId: "older-blog", projectId: "blog", source: "cli", agentRunId: null, terminalId: null, active: false },
    ]);
    expect(sessions[0]).toMatchObject({
      title: "pid prompt",
      preview: "pid answer",
      model: "claude-opus-4-5",
      startedAt: at(9),
      lastActiveAt: at(11),
      messages: 1,
      usage: { totalTokens: 100 },
      cwd: site,
    });

    expect((await service.sessions({ projectId: "blog" })).map((session) => session.sessionId)).toEqual(["from-cwd", "older-blog"]);
    expect((await service.sessions({ limit: 2 })).map((session) => session.sessionId)).toEqual(["from-pid", "from-cwd"]);
  });

  test("subagent usage counts toward its parent session", async () => {
    const { root, service } = setup();
    const path = writeTranscript(root, site, "parent", [user("go"), assistant("m1", "done")]);
    const subagents = join(path.replace(/\.jsonl$/, ""), "subagents");
    mkdirSync(subagents, { recursive: true });
    writeFileSync(join(subagents, "agent-1.jsonl"), jsonl([assistant("sub1", "sub", { model: "claude-haiku-4-5" })], site, "parent"));
    const [session] = await service.sessions();
    expect(session).toMatchObject({ sessionId: "parent", title: "go", preview: "done", messages: 2, usage: { totalTokens: 200 } });
    const report = await service.usage({ days: 1 });
    expect(report.totals).toMatchObject({ messages: 2, sessions: 1 });
    expect(report.models.map((model) => model.model).sort()).toEqual(["claude-haiku-4-5", "claude-opus-4-5"]);
  });
});

describe("GET /v1/usage and /v1/sessions", () => {
  let t: TestController;

  beforeAll(async () => {
    const workspace = makeTempDir("usage");
    t = await startTestController({ workspace });
  });

  afterAll(async () => {
    await t.stop();
  });

  test("require the token", async () => {
    expect((await fetch(`${t.baseUrl}/v1/usage`)).status).toBe(401);
    expect((await fetch(`${t.baseUrl}/v1/sessions`)).status).toBe(401);
  });

  test("answer with zeros before Claude Code ever ran", async () => {
    const usage = await t.json<UsageReport>("GET", "/v1/usage?days=7");
    expect(usage.status).toBe(200);
    expect(UsageReportSchema.parse(usage.body).daily).toHaveLength(7);
    const sessions = await t.json("GET", "/v1/sessions");
    expect(sessions).toEqual({ status: 200, body: [] });
  });

  test("report transcripts and reject bad queries", async () => {
    const cwd = join(t.workspace, "projects", "site");
    const now = new Date().toISOString();
    writeTranscript(t.config.claudeConfigDir, cwd, "live", [user("ship it", { timestamp: now }), assistant("m1", "shipped", { timestamp: now })], Date.now());

    const usage = await t.json("GET", "/v1/usage");
    expect(usage.status).toBe(200);
    const report = UsageReportSchema.parse(usage.body);
    expect(report.days).toBe(30);
    expect(report.totals).toMatchObject({ messages: 1, sessions: 1, totalTokens: 100 });
    expect(report.projects).toMatchObject([{ projectId: "site", sessions: 1 }]);

    const sessions = await t.json("GET", "/v1/sessions?projectId=site&limit=5");
    expect(sessions.status).toBe(200);
    expect(ClaudeSessionListSchema.parse(sessions.body)).toMatchObject([
      { sessionId: "live", projectId: "site", title: "ship it", preview: "shipped", source: "cli", active: false },
    ]);
    expect((await t.json("GET", "/v1/sessions?projectId=blog")).body).toEqual([]);

    for (const path of ["/v1/usage?days=0", "/v1/usage?days=91", "/v1/sessions?limit=0", "/v1/sessions?projectId=..%2Fx"]) {
      const response = await t.json<{ error: { code: string } }>("GET", path);
      expect(response.status).toBe(400);
      expect(response.body.error.code).toBe("bad_request");
    }
  });
});
