export const PALETTE_LABELS = {
  dialog: "Command menu",
  placeholder: "Type a command or search…",
  results: "Commands",
  empty: (query: string) => `No results for “${query}”`,
  emptyHint: "Try a page, a project or a setting.",
  navigate: "Navigate",
  select: "Open",
  close: "Close",
  groups: {
    recent: "Recent",
    navigation: "Navigation",
    projects: "Projects",
    actions: "Actions",
    settings: "Settings",
    appearance: "Appearance",
    window: "Window",
  },
  goTo: (title: string) => `Go to ${title}`,
  openProject: (name: string) => `Open ${name}`,
  confidential: "Confidential",
  newConversation: "New conversation",
  refresh: "Refresh connection",
  rediscover: "Rediscover the sandbox",
  setupWizard: "Run the setup wizard",
  openSettings: "Open Settings",
  settingsSection: (title: string) => `${title} settings`,
  appearance: { system: "Use system appearance", light: "Use light appearance", dark: "Use dark appearance" },
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomReset: "Reset zoom",
  closeWindow: "Close window",
  quit: "Quit Monolith",
  keywords: {
    newConversation: ["agent", "claude", "chat", "ask"],
    refresh: ["reload", "poll", "health"],
    rediscover: ["docker", "discover", "connect"],
    setupWizard: ["onboarding", "docker", "install", "android", "emulator", "image"],
    settings: ["preferences", "options"],
    appearance: ["theme", "dark", "light", "mode"],
    zoom: ["scale", "size", "font"],
    quit: ["exit"],
  },
} as const;

export const PALETTE_GROUP_ORDER: readonly string[] = [
  PALETTE_LABELS.groups.recent,
  PALETTE_LABELS.groups.navigation,
  PALETTE_LABELS.groups.projects,
  PALETTE_LABELS.groups.actions,
  PALETTE_LABELS.groups.settings,
  PALETTE_LABELS.groups.appearance,
  PALETTE_LABELS.groups.window,
];
