export const ATTACHMENT_LABELS = {
  attach: "Attach",
  images: "Images…",
  files: "Files…",
  paste: "Paste image",
  imagesTitle: "Attach images",
  filesTitle: "Attach files",
  imagesFilter: "Images",
  remove: (name: string) => `Remove ${name}`,
  retry: (name: string) => `Retry ${name}`,
  tooLarge: (name: string, limit: string) => `${name} is larger than ${limit}.`,
  tooMany: (limit: number) => `You can attach up to ${limit} files to one message.`,
  noPath: (name: string) => `${name} isn't a local file, so it can't be attached.`,
  notPicked: (name: string) => `${name} wasn't chosen in the file picker, so it can't be attached.`,
  unreadable: (name: string, error: string) => `Couldn't read ${name}: ${error}`,
  emptyClipboard: "There's no image on the clipboard to paste.",
  promptImage: "Take a look at this image.",
  promptImages: "Take a look at these images.",
  promptFile: "Take a look at the attached file.",
  promptFiles: "Take a look at the attached files.",
} as const;
