import type { SyncKind } from "../../../../../shared/contracts/syncback";

export const SYNC_LABELS = {
  notLinked:
    "Not linked on this computer. Run tesseract --sync in the project's checkout to link it, then changes made in the sandbox can be synced back.",
  neverPushed: (path: string) => `The sandbox has no push baseline yet. Run tesseract --sync in ${path}.`,
  error: (error: string) => `Couldn't read sandbox changes: ${error}`,
  hostPath: "Host folder",
  pushed: "Linked",
  got: "Last get",
  baseline: "Sandbox baseline",
  never: "—",
  changes: "Sandbox changes",
  changesSubtitle: (count: string, size: string) => `${count} · ${size}`,
  changesEmpty: "Nothing to sync. The host folder matches the sandbox.",
  changesList: "Changed files",
  conflict: "changed on the host since the push",
  conflictBadge: "Host edit",
  sync: "Sync to host",
  get: "Sync from host",
  revert: "Revert last sync",
  discard: "Discard changes",
  actions: "Sync actions",
  snapshots: "Snapshots",
  snapshotsSubtitle: "Taken before every sync to host; the newest 20 are kept",
  snapshotsEmpty: "No syncs yet.",
  snapshotsList: "Snapshots",
  snapshotMeta: (files: string, when: string) => `${files} · ${when}`,
  reverted: "Reverted",
  requests: "Recent requests",
  requestsEmpty: "No sync requests yet.",
  requestsList: "Sync requests",
  requestMeta: (source: string, when: string) => `from ${source} · ${when}`,
  confirm: (count: string) => `Sync ${count}`,
  confirmForce: "Overwrite and Sync",
  cancel: "Cancel",
  cancelRequest: "Cancel",
  revertTitle: (id: string) => `Revert snapshot ${id}?`,
  revertBody: (count: string) => `Puts back the ${count} as they were before that sync. The sandbox is not changed.`,
  revertConfirm: "Revert",
  getTitle: (path: string) => `Sync from ${path}?`,
  getBody: (path: string) => `Copies what changed in ${path} since the last push or sync into the sandbox.`,
  getConflicts: (count: string, files: string) =>
    `The last sync from this computer stopped because the sandbox also edited ${count}. Syncing again overwrites them; copies of the sandbox versions are kept on the sandbox.\n\n${files}`,
  getForce: "Overwrite and Sync",
  discardTitle: (count: string) => `Discard ${count} in the sandbox?`,
  discardBody: (files: string) =>
    `Puts these files back as they were at the last sync. Added files are deleted. The host folder is not changed.\n\n${files}`,
  discardSkipped: (count: string) => `\n\n${count} can't be restored by the sandbox and stay as they are.`,
  discardConfirm: "Discard",
  discarded: (count: string) => `Discarded ${count} in the sandbox`,
  discardedNone: "Nothing was discarded",
  discardUnavailable: (count: string, files: string) => `${count} kept, the sandbox has no copy of the synced version: ${files}`,
  discardBackup: (path: string) => `Previous versions saved in ${path}`,
  discardFailed: (error: string) => `Couldn't discard the sandbox changes: ${error}`,
  dismiss: "Dismiss",
  more: (count: number) => `… and ${count} more`,
  queued: { pull: "Sync requested", get: "Sync from host requested", revert: "Revert requested" } satisfies Record<SyncKind, string>,
  file: "file",
} as const;

export const SYNC_HINTS = {
  pull: "Copy the sandbox changes into the host folder",
  get: "Copy the host folder's changes into the sandbox",
  revert: "Undo the last sync to host on this computer",
  discard: "Throw away the sandbox changes and restore the synced versions",
} as const;

export const SYNC_BLOCKED = {
  loading: "Loading the sandbox changes…",
  unavailable: "The sandbox changes couldn't be read",
  notLinked: "Not linked on this computer. Run tesseract --sync in the checkout first",
  neverPushed: "Never pushed. Run tesseract --sync in the checkout first",
  active: "A sync request is already in progress",
  nothingToSync: "Nothing to sync. The host folder matches the sandbox",
  nothingToDiscard: "Nothing to discard. The sandbox matches the last sync",
  notDiscardable: "The sandbox has no copy of the synced versions of these files",
  noSnapshot: "No sync to revert",
} as const;

export const SYNC_KINDS: Readonly<Record<string, string>> = { pull: "Sync to host", revert: "Revert", get: "Sync from host" };

export const RESULT_LABELS = {
  added: "added",
  modified: "modified",
  deleted: "deleted",
  restored: "restored",
  recreated: "recreated",
  removed: "removed",
  noFiles: "no files",
  noChanges: "no changes",
  reverted: (where: string, counts: string) => `Reverted the last sync in ${where} (${counts})`,
  pulled: (files: string, where: string, counts: string) => `Pulled ${files} into ${where} (${counts})`,
  sent: (files: string, counts: string) => `Sent ${files} to the sandbox (${counts})`,
  upToDate: "Sandbox already up to date",
  lines: (insertions: number, deletions: number) => `+${insertions} −${deletions}`,
  gitUpdated: (files: string) => `updated .git (${files})`,
  backupKept: (path: string) => `sandbox edits kept in ${path}`,
  separator: " · ",
  listSeparator: ", ",
} as const;

export const SYNC_REVIEW_LABELS = {
  title: "Review sync to host",
  destination: (path: string) => `Into ${path}`,
  stats: (count: string, size: string) => `${count} · ${size}`,
  filter: "Filter files",
  noMatch: "No files match",
  conflicts: (count: string) => `${count} changed on this computer since the push and will be overwritten.`,
  select: "Select a file to see what changes on the host",
  loading: "Loading the diff…",
  kinds: { added: "New file", modified: "Modified", deleted: "Deleted on the host" } as Readonly<Record<string, string>>,
  kindCount: (count: number, kind: string) => `${count} ${kind}`,
  added: (count: number) => `+${count}`,
  removed: (count: number) => `−${count}`,
  binary: (before: string, after: string) => `Binary file, ${before} → ${after}`,
  tooLarge: (size: string) => `Too large to preview (${size})`,
  identical: "Same content as the host copy",
  empty: "Empty file",
  truncated: (count: number) => `Diff cut off after ${count} lines`,
  failed: (error: string) => `Couldn't load the diff: ${error}`,
  absent: "none",
  snapshot: "A snapshot is taken first, so Revert can undo this.",
  files: "Files to sync",
  lines: "Diff",
  addSign: "+",
  delSign: "−",
} as const;
