export const PAIR_LABELS = {
  title: "Pair a device",
  instructions: "Scan with the Tesseract app, or open this link on the phone.",
  sandbox: "Sandbox {name} · {url}",
  copy: "Copy link",
  copied: "Pairing link copied",
  copyFailed: "Couldn't copy the pairing link",
  done: "Done",
  secret: "The link contains the API token: share it only with your own devices.",
  offline: "The sandbox is not answering right now. The phone can pair, but it will connect once the sandbox is back.",
  unconfigured: "Connect to a sandbox before pairing a device.",
  setUp: "Set up",
  invalid: "Can't build a pairing link: {error}",
  tabSandbox: "Sandbox",
  tabHost: "This computer",
  hostInstructions: "Scan with the Tesseract app (Host shell), or open this link on the phone.",
  hostCaption: "Host {name} · {url}",
  hostSecret: "The link contains the host token: share it only with your own devices. Phones also need the PIN.",
  hostLoading: "Reading the host shell settings…",
  hostStopped: "The host shell isn't running. Start it so the phone can reach this computer.",
  hostStarting: "Starting the host shell…",
  hostExternal: "The host shell is running outside Tesseract.",
  hostFailed: "The host shell couldn't start: {error}",
  hostNoPin: "No PIN is set yet. Phones need it to unlock the shell.",
  start: "Start",
  setPin: "Set PIN",
  retry: "Retry",
} as const;
