export const BUILDS_LABELS = {
  targets: "Build targets",
  targetsSubtitle: "Detected from the project's package.json and native folders",
  targetsEmpty: "No build targets detected for this project.",
  profiles: "Build profile",
  build: "Build",
  jobs: "Builds",
  jobsEmpty: "No builds yet.",
  cancel: "Cancel build",
  showLogs: "Show logs",
  hideLogs: "Hide logs",
  meta: (profile: string, when: string) => `${profile} · ${when}`,
  artifacts: (count: number) => `${count} artifacts`,
  logsTitle: (target: string) => `Logs · ${target}`,
  cancelTitle: "Cancel this build?",
  cancelBody: (target: string, profile: string) => `${target} (${profile}) stops and its outputs are discarded.`,
  cancelConfirm: "Cancel Build",
  keep: "Keep Building",
  started: (target: string) => `Building ${target}`,
  subtitle: (platform: string, target: string) => `${platform} · ${target}`,
  states: {
    queued: "Queued",
    running: "Running",
    succeeded: "Succeeded",
    failed: "Failed",
    cancelled: "Cancelled",
  },
} as const;
