import {
  AppWindow,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioWaveform,
  Bell,
  Box,
  Camera,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleHelp,
  CircleUser,
  CircleX,
  Clipboard,
  Clock,
  CloudDownload,
  CloudOff,
  CloudUpload,
  Container,
  Copy,
  Cpu,
  Download,
  Ellipsis,
  Eraser,
  ExternalLink,
  Eye,
  File as FileIcon,
  FileArchive,
  FileCode,
  FileText,
  Files,
  FolderOpen,
  GitBranch,
  GitCommitHorizontal,
  Globe,
  Hammer,
  HardDrive,
  History,
  House,
  Image as ImageIcon,
  Images,
  Inbox,
  Info,
  Keyboard,
  Layers,
  Link,
  ListFilter,
  Lock,
  LogOut,
  Maximize2,
  MemoryStick,
  Menu,
  MessageCircle,
  Mic,
  Minimize2,
  Minus,
  Monitor,
  MousePointer2,
  Network,
  Package,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pencil,
  Play,
  Plug,
  Plus,
  QrCode,
  RefreshCw,
  Scan,
  Search,
  Settings,
  Shuffle,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  SquarePen,
  SquareTerminal,
  SquareUser,
  Star,
  SunMoon,
  Tag,
  Trash2,
  TriangleAlert,
  Undo2,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  overview: House,
  sandbox: Box,
  host: Monitor,
  projects: Box,
  project: Box,
  processes: SquareTerminal,
  terminal: SquareTerminal,
  builds: Hammer,
  artifacts: Package,
  files: Files,
  save: Download,
  agents: MousePointer2,
  inbox: Inbox,
  display: Monitor,
  ports: Globe,
  browser: Globe,
  usage: ChartColumn,
  sessions: History,
  context: FileText,
  "file-pdf": FileText,
  pair: QrCode,
  appearance: SunMoon,
  settings: Settings,
  connection: Plug,
  microphone: Mic,
  cpu: Cpu,
  memory: MemoryStick,
  disk: HardDrive,
  network: Network,
  uptime: Clock,
  version: Info,
  info: Info,
  offline: CloudOff,
  error: CircleAlert,
  warning: TriangleAlert,
  success: CircleCheck,
  "status-done": CircleCheck,
  failed: CircleX,
  "status-canceled": CircleX,
  refresh: RefreshCw,
  menu: Menu,
  more: Ellipsis,
  archive: Archive,
  unarchive: ArchiveRestore,
  add: Plus,
  stop: Square,
  play: Play,
  down: ArrowDown,
  sync: CloudDownload,
  "sync-from-host": CloudDownload,
  "sync-to-host": CloudUpload,
  revert: Undo2,
  copy: Copy,
  issues: Copy,
  rename: Pencil,
  external: ExternalLink,
  search: Search,
  docker: Container,
  empty: FolderOpen,
  send: ArrowUp,
  compose: SquarePen,
  chat: MessageCircle,
  branch: GitBranch,
  commit: GitCommitHorizontal,
  tool: Wrench,
  keyboard: Keyboard,
  fullscreen: Maximize2,
  "exit-fullscreen": Minimize2,
  fit: Scan,
  "my-issues": Scan,
  "view-only": Eye,
  back: ArrowLeft,
  forward: ArrowRight,
  expand: ChevronDown,
  "caret-down": ChevronDown,
  collapse: ChevronRight,
  "caret-right": ChevronRight,
  "chevron-left": ChevronLeft,
  sidebar: PanelLeft,
  details: PanelRight,
  delete: Trash2,
  close: X,
  filter: ListFilter,
  "display-options": SlidersHorizontal,
  notifications: Bell,
  favorite: Star,
  views: Layers,
  "status-backlog": CircleDashed,
  "status-todo": Circle,
  "status-progress": CircleDot,
  "status-done-all": CheckCheck,
  assignee: CircleUser,
  label: Tag,
  link: Link,
  check: Check,
  "whats-new": Sparkles,
  "fix-ai": Sparkles,
  team: SquareUser,
  minus: Minus,
  help: CircleHelp,
  logout: LogOut,
  "file-code": FileCode,
  "file-archive": FileArchive,
  smartphone: Smartphone,
  "app-window": AppWindow,
  paste: Clipboard,
  clear: Eraser,
  screenshot: Camera,
  confidential: Lock,
  shuffle: Shuffle,
  attach: Paperclip,
  image: ImageIcon,
  images: Images,
  file: FileIcon,
  audio: AudioWaveform,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export const ICON_SIZE = { xs: 16, sm: 16, md: 16, lg: 24, xl: 32, "2xl": 48, "3xl": 64 } as const;
export type IconSize = keyof typeof ICON_SIZE;
export const ICON_STROKE_WIDTH = 2;
