export const EMULATOR_LABELS = {
  unavailable: (reason: string) => `Can't run on the emulator: ${reason}`,
  started: "Building for the emulator; the app opens there when the build finishes",
  failed: (error: string) => `Couldn't run on the emulator: ${error}`,
  noSerial: "The emulator is not reachable from this machine",
  noScrcpy: "The app runs on the emulator; install scrcpy to see its screen here",
  viewerFailed: (error: string) => `Couldn't show the emulator: ${error}`,
  title: (name: string) => `${name} · Android emulator`,
  hostStopped: "The host shell isn't running, so Tesseract can't start the emulator. Turn on Serve host shell in Preferences.",
  hostLoading: "Tesseract is still reading the host shell settings; try again in a moment.",
  hostNoPin: "Set a host shell PIN in Preferences so Tesseract can start the emulator.",
  hostUnavailable: "The host can't run the Android emulator",
  hostFailed: (error: string) => `The host shell couldn't prepare the emulator: ${error}`,
  preferences: "Preferences",
  isolationOff: "The host shell runs with TESSERACT_EMULATOR_ISOLATION=none, so the sandbox may not use its emulator",
  stopping: "The emulator is stopping; try again in a moment",
  noAvd: "This computer has no Android virtual device; create one in the setup wizard",
  setupEmulator: "Set up emulator",
  emulatorFailed: (error: string) => `The emulator failed: ${error}`,
  unknownError: "unknown error",
  stopTimeout: "The emulator did not stop in time",
  bootTimeout: (minutes: number) => `The emulator did not boot within ${minutes} minutes`,
  targetTimeout: (seconds: number) => `The sandbox did not pick up the emulator within ${seconds} seconds`,
  progress: {
    checking: "Checking the emulator…",
    stopping: "Stopping the emulator…",
    starting: "Starting the emulator…",
    linking: "Linking the emulator to the sandbox…",
    booting: "Waiting for the emulator…",
  },
  restartTitle: "Restart the emulator isolated?",
  restartBody: (avd: string) =>
    `The running emulator was started outside Tesseract, so the sandbox may not use it. Tesseract stops it and starts ${avd} in an isolated network.`,
  restartConfirm: "Restart",
  relinkTitle: "Link this sandbox instead?",
  relinkBody: (url: string) => `The host emulator is linked to ${url}. Linking it to this sandbox ends that link.`,
  relinkConfirm: "Link",
  cancel: "Cancel",
} as const;
