export const DONE_LABELS = {
  description: "Everything below can be changed later in Settings.",
  summary: "Summary",
  rows: {
    docker: "Docker",
    claude: "Claude Code",
    sandbox: "Sandbox",
    android: "Android emulator",
    pair: "Phone",
  },
  dockerKinds: {
    engine: "Docker Engine",
    desktop: "Docker Desktop",
    rootless: "Docker (rootless)",
    podman: "Podman",
    colima: "Colima",
    orbstack: "OrbStack",
    unknown: "Docker",
  },
  notChecked: "Not checked",
  ready: "Ready",
  signedInAs: (email: string) => `Signed in as ${email}`,
  signedIn: "Signed in",
  notSignedIn: "Not signed in",
  notBuilt: "Not built yet",
  skipped: "Skipped",
  pairingReady: "Pairing link ready",
  autostart: "Start the sandbox when Monolith opens",
  finishFailed: (error: string) => `Couldn't finish setup: ${error}`,
} as const;
