import type { ContainerState, RouteScheme, RouteStatus, ServerContainer } from "../../../shared/contracts/containers";
import type { MemoryUnit } from "./constants";
import type { ContainerAction } from "./types";

export const CONTAINERS_LABELS = {
  title: "Containers",
  refresh: "Refresh",
  newContainer: "New container",
  separator: " · ",
  none: "—",
  states: { running: "Running", starting: "Starting", stopped: "Stopped", error: "Error" } satisfies Record<ContainerState, string>,
  tunnel: { none: "No public URLs", running: "Running", stopped: "Stopped" } satisfies Record<ServerContainer["tunnel"], string>,
  list: {
    loading: "Loading containers…",
    unavailable: "Containers aren't available",
    empty: "No containers yet",
    emptyMessage: "A container is a Linux server with its own Docker that joins your tailnet, so you can SSH into it and publish its ports.",
    create: "New container",
    settings: "Open settings",
    tryAgain: "Try again",
    group: "All containers",
    offTailnet: "Not on the tailnet",
    routes: (count: number) => (count === 0 ? null : `${count} ${count === 1 ? "URL" : "URLs"}`),
  },
  resources: {
    cpus: (count: number) => `${count} ${count === 1 ? "CPU" : "CPUs"}`,
    memory: (value: string, unit: string) => `${value} ${unit}`,
    unlimited: "No limit",
    shared: "Shared resources",
  },
  actions: {
    start: "Start",
    stop: "Stop",
    restart: "Restart",
    delete: "Delete",
    done: { start: (name: string) => `${name} started`, stop: (name: string) => `${name} stopped`, restart: (name: string) => `${name} restarted` } satisfies Record<
      ContainerAction,
      (name: string) => string
    >,
    failed: (action: ContainerAction, name: string, error: string) => `Couldn't ${action} ${name}: ${error}`,
    deleted: (name: string) => `${name} deleted`,
    deleteFailed: (name: string, error: string) => `Couldn't delete ${name}: ${error}`,
  },
  detail: {
    loading: "Loading container…",
    notFound: "Container not found",
    notFoundMessage: (name: string) => `There's no container named ${name} on this computer.`,
    back: "Back to containers",
    properties: "Properties",
    status: "Status",
    dnsName: "Tailnet name",
    ip: "Tailnet IP",
    cpus: "CPUs",
    memory: "Memory",
    image: "Image",
    tunnel: "Cloudflare tunnel",
    created: "Created",
    ssh: "SSH",
    sshHint: "Tailscale SSH. Your tailnet policy decides who can log in.",
    offTailnet: "This container isn't on your tailnet. Add a Tailscale auth key in settings, then recreate it.",
    openSettings: "Open settings",
    urls: "Public URLs",
    urlsSubtitle: "Published through Cloudflare. Services must listen on 0.0.0.0.",
    addUrl: "Add URL",
    noUrls: "No public URLs yet.",
    logs: "Logs",
    logsEmpty: "No output yet.",
    refreshLogs: "Refresh",
  },
  remove: {
    heading: (name: string) => `Delete ${name}?`,
    body: (name: string, urls: number) =>
      `${name} is stopped and deleted with all of its data, including everything in its Docker.${
        urls > 0 ? ` Its ${urls === 1 ? "public URL is" : `${urls} public URLs are`} removed from Cloudflare too.` : ""
      } This can't be undone.`,
    confirm: "Delete",
    cancel: "Cancel",
  },
  create: {
    title: "New container",
    context: "Containers",
    name: "Name",
    nameHint: "Lowercase letters, digits and dashes. It's also the container's name on your tailnet.",
    resources: "Resources",
    cpus: "CPUs",
    memory: "Memory",
    optional: "Optional",
    resourcesHint: "Leave empty to share this computer's resources without a limit.",
    units: { gb: "GB", mb: "MB" } satisfies Record<MemoryUnit, string>,
    unit: "Memory unit",
    submit: "Create",
    cancel: "Cancel",
    creating: (name: string) => `Creating ${name}…`,
    created: (name: string) => `${name} is ready`,
    failed: (error: string) => `Couldn't create the container: ${error}`,
    nameRequired: "Enter a name.",
    invalidCpus: "Enter a number of CPUs, like 2 or 0.5.",
    invalidMemory: "Enter an amount of memory, like 4.",
    noSysbox: "Containers run under the sysbox runtime, which isn't installed on this computer.",
    installSysbox: "Install sysbox",
    noImage: "The server image hasn't been built yet.",
    buildImage: "Build image",
    building: "Building the server image…",
    buildFailed: (error: string) => `Couldn't build the image: ${error}`,
    cancelBuild: "Cancel build",
    noTailscale: "No Tailscale auth key is set, so the container won't join your tailnet.",
  },
} as const;

export const DOMAINS_LABELS = {
  title: "Domains",
  refresh: "Check again",
  resync: "Re-sync",
  resynced: "Public URLs are in sync with Cloudflare",
  resyncFailed: (error: string) => `Couldn't sync with Cloudflare: ${error}`,
  security: {
    title: "How public URLs work",
    message:
      "Traffic reaches a container through Cloudflare's outbound tunnel, so no ports are opened on this computer and the tailnet name is never published. Only the hostname → port pairs listed here are reachable; everything else returns 404. Services inside the container must listen on 0.0.0.0, not 127.0.0.1, for the tunnel to reach them.",
  },
  routes: {
    title: "Public URLs",
    subtitle: "Every hostname published from a container on this computer.",
    add: "Add URL",
    empty: "No public URLs yet.",
    needsCloudflare: "Connect Cloudflare to publish URLs.",
    target: (container: string, port: number) => `${container} · port ${port}`,
    port: (port: number) => `Port ${port}`,
    open: "Open in browser",
    copy: "Copy URL",
    remove: "Remove",
    removed: (hostname: string) => `${hostname} removed`,
    removeFailed: (hostname: string, error: string) => `Couldn't remove ${hostname}: ${error}`,
    status: { active: "Active", pending: "Pending", error: "Error" } satisfies Record<RouteStatus, string>,
  },
  add: {
    title: "Add public URL",
    context: "Domains",
    container: "Container",
    subdomain: "Subdomain",
    subdomainPlaceholder: "app",
    zone: "Domain",
    hostnameHint: (hostname: string) => `Published as https://${hostname}`,
    apexHint: "Leave the subdomain empty to use the domain itself.",
    port: "Port",
    scheme: "Protocol",
    schemes: { http: "HTTP", https: "HTTPS" } satisfies Record<RouteScheme, string>,
    schemeHint: "How the tunnel talks to the service. Visitors always use HTTPS.",
    submit: "Add URL",
    cancel: "Cancel",
    added: (hostname: string) => `${hostname} is published`,
    failed: (error: string) => `Couldn't add the URL: ${error}`,
    invalidPort: "Enter a port between 1 and 65535.",
    noContainer: "Create a container first.",
    noZones: "Connect Cloudflare first. Domains come from the zones your token can edit.",
  },
  cloudflare: {
    title: "Cloudflare",
    description: "Public URLs use a Cloudflare Tunnel per container and DNS records in your Cloudflare zones.",
    status: "Account",
    connected: (zones: number) => `Connected · ${zones} ${zones === 1 ? "domain" : "domains"}`,
    disconnected: "Not connected",
    badge: { connected: "Connected", disconnected: "Not connected", error: "Error" },
    zones: "Domains",
    noZones: "The token can't see any zones.",
    zoneList: (names: readonly string[]) => names.join(", "),
    token: "API token",
    tokenPlaceholder: "Paste a Cloudflare API token",
    permissions: "Create a custom token with these permissions: Zone · DNS · Edit, Account · Cloudflare Tunnel · Edit, and Zone · Zone · Read.",
    createToken: "Create a token",
    connect: "Connect",
    connectedToast: "Cloudflare connected",
    connectFailed: (error: string) => `Couldn't connect Cloudflare: ${error}`,
    disconnect: "Disconnect",
    disconnectedToast: "Cloudflare disconnected",
    disconnectFailed: (error: string) => `Couldn't disconnect Cloudflare: ${error}`,
  },
} as const;

export const TAILSCALE_LABELS = {
  title: "Tailscale",
  description: "Each container joins your tailnet as its own machine, reachable with ssh root@<name>.",
  authKey: "Auth key",
  authKeyPlaceholder: "tskey-auth-…",
  configured: "A key is saved. Paste a new one to replace it.",
  badge: { saved: "Saved", missing: "Not set" },
  missing: "No key yet. Containers won't join your tailnet.",
  tags: "Tags",
  tagsHint: "Comma-separated. Saved together with the key.",
  help: "Create a reusable, pre-approved auth key tagged tag:tesseract-server in the Tailscale admin console.",
  openKeys: "Open the admin console",
  acl: "Suggested policy: members can SSH into tag:tesseract-server, and tag:tesseract-server is granted nothing.",
  openAcl: "Edit the policy",
  save: "Save",
  clear: "Remove key",
  saved: "Tailscale auth key saved",
  cleared: "Tailscale auth key removed",
  failed: (error: string) => `Couldn't save the auth key: ${error}`,
} as const;
