export const DIALOG_SAMPLES = {
  title: "New project",
  context: "Sandbox",
  body: "Projects live in the sandbox workspace. Pick a template or start from an empty folder.",
  cancel: "Cancel",
  create: "Create project",
  formTitle: "Rename project",
  formSubtitle: "The folder in the sandbox workspace is renamed too.",
  titlePlaceholder: "Project name",
  titleValue: "hybrid-pos",
  groupTitle: "Details",
  branch: "Default branch",
  branchValue: "main",
  remote: "Remote URL",
  remoteValue: "git@github.com:theone/hybrid-pos.git",
  description: "Leave the remote empty to keep the project local.",
  error: "Couldn't rename the project: name already taken",
  save: "Save",
  confirmHeading: "Delete hybrid-pos?",
  confirmBody: "The project folder, its builds and its conversations are removed from the sandbox. This can't be undone.",
  confirmDelete: "Delete",
  chooseHeading: "Open in emulator",
  chooseBody: "Pick the virtual device to boot.",
  chooseConfirm: "Start",
  chooseOptions: [
    { id: "pixel-8", label: "Pixel 8 · API 35" },
    { id: "pixel-tablet", label: "Pixel Tablet · API 34" },
  ],
  openShell: "DialogShell",
  openForm: "FormDialog",
  openConfirm: "ConfirmDialog",
  openPair: "PairDialog",
  openPin: "HostPinDialog",
  openUnlock: "HostUnlockDialog",
} as const;

export const SAMPLE_PIN_DELAY_MS = 600;
