export const ANDROID_LABELS = {
  unsupported: {
    linuxArm: "Google doesn't publish the Android emulator for Linux on ARM.",
    windowsArm: "Google doesn't publish the Android emulator for Windows on ARM.",
    other: "The Android emulator isn't available on this platform.",
  },
  catalog: {
    failed: (error: string) => `Couldn't load Google's package list: ${error}`,
    http: (status: number, url: string) => `HTTP ${status} from ${url}`,
    timeout: "The request timed out",
    missing: (path: string) => `Google's package list has no ${path} for this computer`,
    notLoaded: "Load the package list before installing",
    unknownPackage: (path: string) => `Unknown package ${path}`,
    unknownLicense: (id: string) => `Unknown license ${id}`,
    invalidOverride: (name: string, value: string) => `${name} must be an http(s) URL, not ${value}`,
  },
  install: {
    busy: "An installation is already running",
    invalidPlan: "The install plan needs an SDK folder and a list of packages",
    cancelled: "The installation was cancelled",
    corrupt: (pkg: string) => `${pkg}: the download is corrupt (checksum mismatch)`,
    sizeMismatch: (pkg: string) => `${pkg}: the download is incomplete`,
    stalled: (pkg: string) => `${pkg}: the download stalled for 30 seconds`,
    http: (pkg: string, status: number) => `${pkg}: the server answered HTTP ${status}`,
    freeSpace: (free: string, dir: string) => `Only ${free} GB free in ${dir}`,
    needsEmulator: (min: string) => `This system image needs emulator ${min} or newer`,
    unsafeEntry: (name: string) => `The archive contains an unsafe path: ${name}`,
    unsafeLink: (name: string) => `The archive contains a link that leaves the package: ${name}`,
    log: {
      skip: (pkg: string, revision: string) => `${pkg} ${revision} is already installed`,
      download: (pkg: string, url: string) => `Downloading ${pkg} from ${url}`,
      resume: (pkg: string, received: number) => `Resuming ${pkg} at ${received} bytes`,
      retry: (pkg: string, error: string) => `${pkg}: ${error}; retrying`,
      verify: (pkg: string) => `Verifying ${pkg}`,
      extract: (pkg: string, dir: string) => `Extracting ${pkg} into ${dir}`,
      installed: (pkg: string, revision: string) => `Installed ${pkg} ${revision}`,
      avd: (name: string, path: string) => `Created the virtual device ${name} in ${path}`,
    },
  },
  accel: {
    kvmTitle: "KVM",
    kvmOk: "/dev/kvm is available",
    kvmMissing: "KVM isn't available: turn on virtualization (VT-x / AMD-V) in the BIOS/UEFI settings and load the kvm_intel or kvm_amd module",
    kvmModprobe: (module: string) => `sudo modprobe ${module}`,
    kvmAccessTitle: "Access to /dev/kvm",
    kvmAccessOk: "You can use /dev/kvm",
    kvmAccess: "You can't use /dev/kvm yet",
    kvmGroupCommand: "sudo usermod -aG kvm $USER",
    isolationTitle: "Network isolation",
    isolationOk: "The emulator can run in its own network namespace",
    isolation: "Network isolation for the emulator isn't available",
    isolationCommands: [
      "sudo sysctl -w kernel.unprivileged_userns_clone=1",
      "sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0",
    ],
    whpxTitle: "Windows Hypervisor Platform",
    whpxOk: "Windows Hypervisor Platform is on",
    whpxOff: "Windows Hypervisor Platform is off",
    hvfTitle: "Hypervisor.framework",
    hvfOk: "Hypervisor.framework is available",
    hvfMissing: "This Mac doesn't support Hypervisor.framework",
    emulatorTitle: "Emulator acceleration check",
    emulatorTimeout: "The emulator's acceleration check did not answer in time",
    emulatorNoOutput: "The emulator's acceleration check printed nothing",
    hints: {
      cpu: "This processor lacks the virtualization extensions (VT-x / SVM / NX) the emulator needs.",
      notInstalled: "The hypervisor isn't installed.",
      missingDevice: "/dev/kvm is missing: turn on virtualization in the BIOS/UEFI settings and load the KVM module.",
      disabled: "Virtualization (VT-x / NX) is turned off in the BIOS/UEFI settings.",
      permission: "You don't have permission to use /dev/kvm: add yourself to the kvm group and sign in again.",
      ioctl: "The hypervisor could not be opened; restart the computer and try again.",
    },
  },
  avd: {
    invalidName: "Use letters, digits, dots, dashes and underscores only",
    exists: (name: string) => `An AVD named ${name} already exists`,
    missing: (name: string) => `There is no virtual device named ${name}`,
    imageMissing: (path: string, sdk: string) => `The system image ${path} isn't installed in ${sdk}`,
    invalidImage: (path: string) => `${path} isn't a Google APIs system image`,
    invalidResources: "Memory must be between 1024 and 8192 MB, with at least one CPU core",
    notListed: (name: string) => `The emulator doesn't see the new virtual device ${name}`,
    tagDisplay: "Google APIs",
    invalidDevice: (profile: string, known: string) => `Unknown device profile ${profile}; use one of ${known}`,
    invalidStorage: "Internal storage must be between 2 and 64 GB",
    invalidSpec: (field: string) => `The virtual device has an invalid ${field}`,
  },
  emulator: {
    notInstalled: (sdk: string) => `The Android emulator is not installed in ${sdk}`,
    running: "The emulator is already running",
    inUse: (name: string) => `${name} is running; stop the emulator first`,
    noPort: "No free emulator port between 5554 and 5682",
    exited: (code: number | null, line: string | null) => {
      const head = code === null ? "The emulator stopped" : `The emulator exited with code ${code}`;
      return line ? `${head}: ${line}` : head;
    },
    bootTimeout: "The emulator did not boot within 5 minutes",
    started: (avd: string, port: number) => `Starting ${avd} on port ${port}`,
    booted: (avd: string, serial: string) => `${avd} booted (${serial})`,
  },
} as const;
