import type { DockerKind } from "../../../../shared/contracts/docker";

export const SANDBOX_SETTINGS_LABELS = {
  title: "Sandbox",
  refresh: "Check again",
  separator: " · ",
  docker: {
    title: "Docker",
    description: "Tesseract runs the sandbox in Docker on this computer.",
    engine: "Engine",
    checking: "Checking Docker…",
    kinds: {
      engine: "Docker Engine",
      desktop: "Docker Desktop",
      rootless: "Docker Engine (rootless)",
      podman: "Podman",
      colima: "Colima",
      orbstack: "OrbStack",
      unknown: "Docker",
    } satisfies Record<DockerKind, string>,
    resources: (cpus: number, memGb: string) => `${cpus} CPUs · ${memGb} GB`,
    badge: {
      checking: "Checking…",
      running: "Running",
      stopped: "Stopped",
      permission: "No access",
      unresponsive: "Not responding",
      missing: "Not installed",
    },
    notInstalled: "The docker command was not found on this computer",
    fix: "Docker needs attention before the sandbox can run.",
    openSetup: "Open setup",
  },
  stack: {
    title: "Sandbox",
    description: "The containers that run Claude Code, your builds and the virtual display.",
    status: "Status",
    project: (project: string, count: number) => `Compose project ${project} · ${count} ${count === 1 ? "container" : "containers"}`,
    image: "Image",
    built: (image: string, when: string) => `${image} · built ${when}`,
    notBuilt: (image: string) => `${image} · not built yet`,
    badge: {
      unconfigured: "Not set up",
      running: "Running",
      partial: "Partly running",
      stopped: "Stopped",
    },
    unconfigured: "No sandbox is set up on this computer yet.",
    setUp: "Set up…",
    autostart: "Start with Tesseract",
    autostartSubtitle: "Start the sandbox whenever Tesseract opens",
    start: "Start",
    stop: "Stop",
    started: "Sandbox started",
    stopped: "Sandbox stopped",
    startFailed: (error: string) => `Couldn't start the sandbox: ${error}`,
    stopFailed: (error: string) => `Couldn't stop the sandbox: ${error}`,
    autostartFailed: (error: string) => `Couldn't save the setting: ${error}`,
  },
  tools: {
    pending: "Rebuild the image to apply these changes. The sandbox restarts when the build finishes.",
    reset: "Reset",
    rebuild: "Rebuild image",
  },
  rebuild: {
    heading: "Rebuild the sandbox image?",
    body: "The build runs in the background and can take a while. The sandbox restarts when it finishes, which stops running agents and processes.",
    confirm: "Rebuild",
    cancel: "Cancel",
    started: "Rebuilding the sandbox image",
    failed: (error: string) => `Couldn't start the build: ${error}`,
  },
  build: {
    title: "Build",
    cancel: "Cancel build",
    cancelFailed: (error: string) => `Couldn't cancel the build: ${error}`,
  },
} as const;
