import { API_PREFIX, UI_PREFIX, type SYNC_REQUEST_STATUSES } from "./constants";
import { buildFragment, buildQuery } from "./url";

export type ProjectFilter = { projectId?: string };
export type LogTail = { tail?: number };
export type TicketParam = { ticket?: string };
export type BuildOutputParams = { path: string; ticket?: string };
export type UsageFilter = { days?: number };
export type SessionsFilter = { limit?: number; projectId?: string };
export type InboxFilter = { limit?: number; unread?: boolean };
export type SyncRequestFilter = { status?: (typeof SYNC_REQUEST_STATUSES)[number] };
export type ForceParam = { force?: boolean };
export type AgentRunFilter = { projectId?: string; archived?: boolean };
export type TerminalPageParams = { ticket: string; session: string };
export type VncPageParams = { ticket: string; password?: string | null };
export type AppRunFilter = { projectId?: string };
export type AndroidScreenFilter = { maxSize?: number; serial?: string; codec?: string };
export type AndroidScreenParams = { ticket: string; maxSize?: number; serial?: string };

const segment = (value: string) => encodeURIComponent(value);
const api = (path: string) => `${API_PREFIX}${path}`;

export const restPaths = {
  health: () => api("/health"),
  authTicket: () => api("/auth/ticket"),
  status: () => api("/status"),
  context: () => api("/context"),
  identity: () => api("/identity"),
  claudeAuth: () => api("/claude/auth"),
  claudeImport: () => api("/claude/import"),
  claudeAccounts: () => api("/claude/accounts"),
  claudeDefaultAccount: () => api("/claude/accounts/default"),
  projects: () => api("/projects"),
  project: (id: string, query?: ForceParam) => api(`/projects/${segment(id)}${buildQuery(query)}`),
  projectGit: (id: string) => api(`/projects/${segment(id)}/git`),
  projectClaudeAccount: (id: string) => api(`/projects/${segment(id)}/claude-account`),
  projectName: (id: string) => api(`/projects/${segment(id)}/name`),
  projectSync: (id: string) => api(`/projects/${segment(id)}/sync`),
  projectSyncChanges: (id: string) => api(`/projects/${segment(id)}/sync/changes`),
  projectSyncExport: (id: string) => api(`/projects/${segment(id)}/sync/export`),
  projectSyncAck: (id: string) => api(`/projects/${segment(id)}/sync/ack`),
  projectSyncDiscard: (id: string) => api(`/projects/${segment(id)}/sync/discard`),
  projectSyncRequests: (id: string) => api(`/projects/${segment(id)}/sync/requests`),
  syncRequests: (query?: SyncRequestFilter) => api(`/sync/requests${buildQuery(query)}`),
  syncRequestClaim: (id: string) => api(`/sync/requests/${segment(id)}/claim`),
  syncRequestComplete: (id: string) => api(`/sync/requests/${segment(id)}/complete`),
  syncRequestCancel: (id: string) => api(`/sync/requests/${segment(id)}/cancel`),
  syncRequestPlan: (id: string) => api(`/sync/requests/${segment(id)}/plan`),
  syncRequestApply: (id: string) => api(`/sync/requests/${segment(id)}/apply`),
  syncHeartbeat: () => api("/sync/heartbeat"),
  processes: (query?: ProjectFilter) => api(`/processes${buildQuery(query)}`),
  process: (id: string) => api(`/processes/${segment(id)}`),
  processLogs: (id: string, query?: LogTail) => api(`/processes/${segment(id)}/logs${buildQuery(query)}`),
  terminals: () => api("/terminals"),
  terminal: (id: string) => api(`/terminals/${segment(id)}`),
  builds: (query?: ProjectFilter) => api(`/builds${buildQuery(query)}`),
  build: (id: string) => api(`/builds/${segment(id)}`),
  buildLogs: (id: string, query?: LogTail) => api(`/builds/${segment(id)}/logs${buildQuery(query)}`),
  artifacts: (query?: ProjectFilter) => api(`/artifacts${buildQuery(query)}`),
  artifact: (id: string) => api(`/artifacts/${segment(id)}`),
  artifactDownload: (id: string, query?: TicketParam) => api(`/artifacts/${segment(id)}/download${buildQuery(query)}`),
  artifactTaildrop: (id: string) => api(`/artifacts/${segment(id)}/taildrop`),
  taildropTargets: () => api("/taildrop/targets"),
  buildOutputs: (query?: ProjectFilter) => api(`/outputs${buildQuery(query)}`),
  buildOutputDownload: (projectId: string, query: BuildOutputParams) =>
    api(`/projects/${segment(projectId)}/outputs/download${buildQuery(query)}`),
  ports: () => api("/ports"),
  usage: (query?: UsageFilter) => api(`/usage${buildQuery(query)}`),
  sessions: (query?: SessionsFilter) => api(`/sessions${buildQuery(query)}`),
  inbox: (query?: InboxFilter) => api(`/inbox${buildQuery(query)}`),
  inboxRead: () => api("/inbox/read"),
  claudeHook: () => api("/hooks/claude"),
  pushDevices: () => api("/push/devices"),
  pushDevice: (token: string) => api(`/push/devices/${segment(token)}`),
  liveActivities: () => api("/push/live-activities"),
  liveActivity: (token: string) => api(`/push/live-activities/${segment(token)}`),
  display: () => api("/display"),
  displayScreenshot: () => api("/display/screenshot"),
  displayBrowser: () => api("/display/browser"),
  displayWindows: () => api("/display/windows"),
  displayWindowActivate: (id: string) => api(`/display/windows/${segment(id)}/activate`),
  displayWindowClose: (id: string) => api(`/display/windows/${segment(id)}/close`),
  agentRuns: (query?: AgentRunFilter) => api(`/agent/runs${buildQuery(query)}`),
  agentRunsArchive: () => api("/agent/runs/archive"),
  agentRunsDelete: () => api("/agent/runs/delete"),
  agentRun: (id: string) => api(`/agent/runs/${segment(id)}`),
  uploads: () => api("/uploads"),
  uploadContent: (id: string, query?: TicketParam) => api(`/uploads/${segment(id)}/content${buildQuery(query)}`),
  transcriptions: () => api("/transcriptions"),
  stt: () => api("/stt"),
  events: () => api("/events"),
  hostLock: () => api("/host/lock"),
  hostUnlock: () => api("/host/unlock"),
  projectRunTargets: (id: string) => api(`/projects/${segment(id)}/run-targets`),
  projectAppRuns: (id: string) => api(`/projects/${segment(id)}/app-runs`),
  appRuns: (query?: AppRunFilter) => api(`/app-runs${buildQuery(query)}`),
  appRun: (id: string) => api(`/app-runs/${segment(id)}`),
  appRunActions: (id: string) => api(`/app-runs/${segment(id)}/actions`),
  android: () => api("/android"),
  androidEmulator: () => api("/android/emulator"),
  androidLink: () => api("/android/link"),
  androidDevices: () => api("/android/devices"),
  androidStream: () => api("/android/stream"),
} as const;

export const wsPaths = {
  events: () => api("/events"),
  terminalStream: (id: string) => api(`/terminals/${segment(id)}/stream`),
  processLogStream: (id: string) => api(`/processes/${segment(id)}/logs/stream`),
  buildLogStream: (id: string) => api(`/builds/${segment(id)}/logs/stream`),
  agentRunStream: (id: string) => api(`/agent/runs/${segment(id)}/stream`),
  vnc: () => api("/display/vnc"),
  androidLink: () => api("/android/link"),
  androidLinkStream: (streamId: string) => api(`/android/link/streams/${segment(streamId)}`),
  androidScreen: (query?: AndroidScreenFilter) => api(`/android/screen${buildQuery(query)}`),
} as const;

export const uiPaths = {
  terminal: (params?: TerminalPageParams) => `${UI_PREFIX}/terminal${buildFragment(params)}`,
  vnc: (params?: VncPageParams) => `${UI_PREFIX}/vnc${buildFragment(params)}`,
  android: (params?: AndroidScreenParams) => `${UI_PREFIX}/android${buildFragment(params)}`,
} as const;

/** Server-side route patterns (Hono/Express `:param` syntax), keyed like the builders above. */
export const routePatterns = {
  rest: {
    health: api("/health"),
    authTicket: api("/auth/ticket"),
    status: api("/status"),
    context: api("/context"),
    identity: api("/identity"),
    claudeAuth: api("/claude/auth"),
    claudeImport: api("/claude/import"),
    claudeAccounts: api("/claude/accounts"),
    claudeDefaultAccount: api("/claude/accounts/default"),
    projects: api("/projects"),
    project: api("/projects/:id"),
    projectGit: api("/projects/:id/git"),
    projectClaudeAccount: api("/projects/:id/claude-account"),
    projectName: api("/projects/:id/name"),
    projectSync: api("/projects/:id/sync"),
    projectSyncChanges: api("/projects/:id/sync/changes"),
    projectSyncExport: api("/projects/:id/sync/export"),
    projectSyncAck: api("/projects/:id/sync/ack"),
    projectSyncDiscard: api("/projects/:id/sync/discard"),
    projectSyncRequests: api("/projects/:id/sync/requests"),
    syncRequests: api("/sync/requests"),
    syncRequestClaim: api("/sync/requests/:id/claim"),
    syncRequestComplete: api("/sync/requests/:id/complete"),
    syncRequestCancel: api("/sync/requests/:id/cancel"),
    syncRequestPlan: api("/sync/requests/:id/plan"),
    syncRequestApply: api("/sync/requests/:id/apply"),
    syncHeartbeat: api("/sync/heartbeat"),
    processes: api("/processes"),
    process: api("/processes/:id"),
    processLogs: api("/processes/:id/logs"),
    terminals: api("/terminals"),
    terminal: api("/terminals/:id"),
    builds: api("/builds"),
    build: api("/builds/:id"),
    buildLogs: api("/builds/:id/logs"),
    artifacts: api("/artifacts"),
    artifact: api("/artifacts/:id"),
    artifactDownload: api("/artifacts/:id/download"),
    artifactTaildrop: api("/artifacts/:id/taildrop"),
    taildropTargets: api("/taildrop/targets"),
    buildOutputs: api("/outputs"),
    buildOutputDownload: api("/projects/:id/outputs/download"),
    ports: api("/ports"),
    usage: api("/usage"),
    sessions: api("/sessions"),
    inbox: api("/inbox"),
    inboxRead: api("/inbox/read"),
    claudeHook: api("/hooks/claude"),
    pushDevices: api("/push/devices"),
    pushDevice: api("/push/devices/:token"),
    liveActivities: api("/push/live-activities"),
    liveActivity: api("/push/live-activities/:token"),
    display: api("/display"),
    displayScreenshot: api("/display/screenshot"),
    displayBrowser: api("/display/browser"),
    displayWindows: api("/display/windows"),
    displayWindowActivate: api("/display/windows/:id/activate"),
    displayWindowClose: api("/display/windows/:id/close"),
    agentRuns: api("/agent/runs"),
    agentRunsArchive: api("/agent/runs/archive"),
    agentRunsDelete: api("/agent/runs/delete"),
    agentRun: api("/agent/runs/:id"),
    uploads: api("/uploads"),
    uploadContent: api("/uploads/:id/content"),
    transcriptions: api("/transcriptions"),
    stt: api("/stt"),
    events: api("/events"),
    hostLock: api("/host/lock"),
    hostUnlock: api("/host/unlock"),
    projectRunTargets: api("/projects/:id/run-targets"),
    projectAppRuns: api("/projects/:id/app-runs"),
    appRuns: api("/app-runs"),
    appRun: api("/app-runs/:id"),
    appRunActions: api("/app-runs/:id/actions"),
    android: api("/android"),
    androidEmulator: api("/android/emulator"),
    androidLink: api("/android/link"),
    androidDevices: api("/android/devices"),
    androidStream: api("/android/stream"),
  },
  ws: {
    events: api("/events"),
    terminalStream: api("/terminals/:id/stream"),
    processLogStream: api("/processes/:id/logs/stream"),
    buildLogStream: api("/builds/:id/logs/stream"),
    agentRunStream: api("/agent/runs/:id/stream"),
    vnc: api("/display/vnc"),
    androidLink: api("/android/link"),
    androidLinkStream: api("/android/link/streams/:id"),
    androidScreen: api("/android/screen"),
  },
  ui: {
    terminal: `${UI_PREFIX}/terminal`,
    vnc: `${UI_PREFIX}/vnc`,
    android: `${UI_PREFIX}/android`,
  },
} as const;
