export const ANDROID_SETTINGS_LABELS = {
  title: "Android",
  refresh: "Refresh",
  devices: {
    title: "Virtual devices",
    description: "Emulators on this computer that the sandbox can run Android builds on.",
    empty: "No virtual devices yet",
    emptySubtitle: "Pick a system image below to create one.",
    subtitle: (image: string, abi: string | null) => (abi ? `${image} · ${abi}` : image),
    unknownImage: "Unknown system image",
    start: "Start",
    stop: "Stop",
    delete: (name: string) => `Delete ${name}`,
    badges: { running: "Running", starting: "Starting…", stopping: "Stopping…" },
    startFailed: (error: string) => `Couldn't start the emulator: ${error}`,
    stopFailed: (error: string) => `Couldn't stop the emulator: ${error}`,
    deleted: (name: string) => `Deleted ${name}`,
    deleteFailed: (error: string) => `Couldn't delete the device: ${error}`,
    emulatorFailed: "The emulator stopped",
  },
  deleteConfirm: {
    heading: (name: string) => `Delete ${name}?`,
    body: "Its apps and data are removed from this computer. The system image stays installed.",
    confirm: "Delete",
    cancel: "Cancel",
  },
  newDevice: {
    title: "Create a virtual device",
    subtitle: "Write a new emulator for the selected system image after the download",
  },
  install: {
    install: "Install",
    installSize: (size: string) => `Install · ${size}`,
    cancel: "Cancel",
    done: "Android packages installed",
    failed: (error: string) => `Couldn't install the packages: ${error}`,
    cancelled: "The download was cancelled. Install resumes where it stopped.",
  },
} as const;
