import type { Platform } from "../../../../shared/runtime";

export const ABOUT_LABELS = {
  title: "About",
  appName: "Tesseract",
  tagline: "Claude Code and your builds in a sandbox on this computer, followed from your phone.",
  version: (version: string, platform: string, arch: string) => `Version ${version} · ${platform} ${arch}`,
  platforms: { linux: "Linux", darwin: "macOS", win32: "Windows" } satisfies Record<Platform, string>,
  separator: " · ",
  updates: {
    title: "Updates",
    row: "Tesseract updates",
    notChecked: "Not checked yet",
    checkedAt: (when: string) => `Checked ${when}`,
    checking: "Checking for updates…",
    upToDate: (when: string) => `Tesseract is up to date · checked ${when}`,
    available: (version: string) => `Tesseract ${version} is available`,
    downloading: (version: string, progress: string) => `Downloading ${version} · ${progress}`,
    ready: (version: string) => `Tesseract ${version} is ready to install`,
    error: (message: string) => `Couldn't check for updates: ${message}`,
    notes: "What's new",
    check: "Check for updates",
    checkAgain: "Check again",
    download: "Download",
    restart: "Restart to update",
    retry: "Try again",
    failed: (error: string) => `Couldn't update Tesseract: ${error}`,
  },
  cli: {
    title: "Command line",
    description: "The tesseract command controls the sandbox from a terminal, like the setup in this app.",
    row: "tesseract command",
    installed: (path: string) => `On your PATH at ${path}`,
    installedBadge: "Installed",
    missing: "Not on your PATH yet",
    conflict: (path: string) => `Another program already uses ${path}`,
    unsupported: "Available in the installed app",
    install: "Install tesseract command",
    installedToast: "The tesseract command is installed",
    failed: (error: string) => `Couldn't install the tesseract command: ${error}`,
    usage: "tesseract --help",
  },
  files: {
    title: "Files",
    config: "Settings file",
    logs: "Logs",
    data: "App data",
    show: "Show in folder",
  },
  relative: {
    now: "just now",
    minutes: (n: number) => `${n} min ago`,
    hours: (n: number) => `${n} h ago`,
    days: (n: number) => (n === 1 ? "yesterday" : `${n} days ago`),
  },
} as const;
