module.exports = {
  preset: "jest-expo",
  setupFiles: ["<rootDir>/tests/mocks/reanimated-setup.js", "react-native-gesture-handler/jestSetup"],
  moduleNameMapper: {
    "\\.css$": "<rootDir>/tests/mocks/style-mock.js",
    "^@/assets/(.*)$": "<rootDir>/assets/$1",
    "^@/modules/theone-island$": "<rootDir>/tests/mocks/theone-island.ts",
    "^@/modules/(.*)$": "<rootDir>/modules/$1",
    "^@/(.*)$": "<rootDir>/src/$1",
    "^expo-secure-store$": "<rootDir>/tests/mocks/expo-secure-store.ts",
    "^expo-sqlite/kv-store$": "<rootDir>/tests/mocks/expo-sqlite-kv-store.ts",
    "^expo-camera$": "<rootDir>/tests/mocks/expo-camera.tsx",
    "^expo-network$": "<rootDir>/tests/mocks/expo-network.ts",
    "^expo-audio$": "<rootDir>/tests/mocks/expo-audio.ts",
    "^expo-image-picker$": "<rootDir>/tests/mocks/expo-image-picker.ts",
    "^expo-document-picker$": "<rootDir>/tests/mocks/expo-document-picker.ts",
    "^expo-clipboard$": "<rootDir>/tests/mocks/expo-clipboard.ts",
    "^expo-file-system$": "<rootDir>/tests/mocks/expo-file-system.ts",
    "^expo-sharing$": "<rootDir>/tests/mocks/expo-sharing.ts",
    "^@shopify/react-native-skia$": "<rootDir>/tests/mocks/react-native-skia.tsx",
    "^react-native-pulsar$": "react-native-pulsar/jest-mock",
    "^react-native-webview$": "<rootDir>/tests/mocks/react-native-webview.tsx",
  },
  testMatch: ["<rootDir>/tests/**/*.test.{ts,tsx}"],
};
