from types import MappingProxyType
from typing import Literal

from . import palette as P

SchemeName = Literal["light", "dark"]
SCHEMES: tuple[SchemeName, ...] = ("light", "dark")

LIGHT = MappingProxyType({
    "background": P.CANVAS,
    "backgroundElement": P.GRAY[100],
    "backgroundSelected": P.GRAY[200],
    "surface": P.CANVAS,
    "surfaceElevated": P.WHITE,
    "surfaceSunken": P.GRAY[50],
    "overlay": "rgba(0, 0, 0, 0.4)",
    "shimmer": "rgba(255, 255, 255, 0.85)",
    "text": P.BLACK,
    "textSecondary": P.GRAY[600],
    "textTertiary": P.GRAY[550],
    "textInverse": P.CANVAS,
    "textOnAccent": P.PERIWINKLE[900],
    "border": P.GRAY[200],
    "borderStrong": P.GRAY[300],
    "divider": P.GRAY[100],
    "accent": P.PERIWINKLE[500],
    "accentPressed": P.PERIWINKLE[600],
    "accentMuted": P.PERIWINKLE[100],
    "accentStrong": P.PERIWINKLE[700],
    "focusRing": P.PERIWINKLE[700],
    "highlight": P.YELLOW[700],
    "success": P.GREEN[700],
    "successMuted": P.GREEN[100],
    "successSolid": P.GREEN[500],
    "warning": P.AMBER[800],
    "warningMuted": P.AMBER[100],
    "warningSolid": P.AMBER[600],
    "danger": P.RED[600],
    "dangerMuted": P.RED[100],
    "dangerSolid": P.RED[500],
    "info": P.BLUE[700],
    "infoMuted": P.BLUE[100],
    "infoSolid": P.BLUE[500],
    "notification": P.RED[600],
    "textOnNotification": P.WHITE,
    "bubbleUser": P.PERIWINKLE[500],
    "bubbleUserText": P.PERIWINKLE[900],
    "bubbleAssistant": P.GRAY[100],
    "bubbleAssistantText": P.BLACK,
    "codeBackground": P.GRAY[50],
    "streamingCursor": P.PERIWINKLE[600],
    "voiceActive": P.VIOLET[500],
})

DARK = MappingProxyType({
    "background": P.BLACK,
    "backgroundElement": P.GRAY[900],
    "backgroundSelected": P.GRAY[800],
    "surface": P.GRAY[950],
    "surfaceElevated": P.GRAY[900],
    "surfaceSunken": P.BLACK,
    "overlay": "rgba(0, 0, 0, 0.6)",
    "shimmer": "rgba(255, 255, 255, 0.12)",
    "text": P.WHITE,
    "textSecondary": P.GRAY[400],
    "textTertiary": P.GRAY[450],
    "textInverse": P.BLACK,
    "textOnAccent": P.PERIWINKLE[900],
    "border": P.GRAY[800],
    "borderStrong": P.GRAY[700],
    "divider": P.GRAY[900],
    "accent": P.PERIWINKLE[500],
    "accentPressed": P.PERIWINKLE[300],
    "accentMuted": "#221C3D",
    "accentStrong": P.PERIWINKLE[300],
    "focusRing": P.PERIWINKLE[400],
    "highlight": P.YELLOW[400],
    "success": P.GREEN[400],
    "successMuted": P.GREEN[900],
    "successSolid": P.GREEN[500],
    "warning": P.AMBER[300],
    "warningMuted": P.AMBER[900],
    "warningSolid": P.AMBER[500],
    "danger": P.RED[400],
    "dangerMuted": P.RED[900],
    "dangerSolid": P.RED[500],
    "info": P.BLUE[300],
    "infoMuted": P.BLUE[900],
    "infoSolid": P.BLUE[400],
    "notification": P.RED[400],
    "textOnNotification": P.BLACK,
    "bubbleUser": P.PERIWINKLE[500],
    "bubbleUserText": P.PERIWINKLE[900],
    "bubbleAssistant": P.GRAY[900],
    "bubbleAssistantText": P.WHITE,
    "codeBackground": P.GRAY[950],
    "streamingCursor": P.PERIWINKLE[500],
    "voiceActive": P.VIOLET[500],
})

COLORS = MappingProxyType({"light": LIGHT, "dark": DARK})


def colors_for(scheme: SchemeName) -> MappingProxyType:
    return COLORS[scheme]
