export const HOST_LABELS = {
  notInCheckout: (entry: string, variable: string) => `The controller is not in this checkout (${entry}); set ${variable}`,
  bunMissing: "Bun is not installed or not on PATH; install it from bun.sh",
  bundledMissing: (path: string) => `The bundled controller is missing (${path}); reinstall Tesseract`,
  emptyOverride: (variable: string) => `${variable} is empty`,
  cliTimeout: "The controller did not answer in time",
  noPairing: "The controller printed no pairing link",
  noToken: "The host pairing link has no token",
  exitedWithCode: (code: number) => `The controller exited with code ${code}`,
  failed: "The controller failed",
  notRunning: "The host shell is not running",
  notAnswering: (url: string) => `The host shell is not answering at ${url}`,
  invalidPin: "The PIN must be 6 to 12 digits",
  noPin: "Set a host shell PIN first",
  locked: "Unlock the host shell with its PIN first",
  invalidAvd: "Pick an Android virtual device",
  invalidSandbox: "The sandbox URL and token are required",
  scrcpyMissing: "The app runs on the emulator; install scrcpy to see its screen here",
  noSerial: "The emulator is not reachable from this machine",
  scrcpyExited: (code: number | null) => `scrcpy exited with code ${code ?? "unknown"}`,
} as const;
