export const SIDEBAR_LABELS = {
  appName: "Tesseract",
  mainMenu: "Main menu",
  noProject: "No project",
  noRuns: "No conversations yet",
  untitledRun: "Untitled conversation",
  expand: "Show conversations",
  collapse: "Hide conversations",
  confidential: "Confidential",
  running: (count: number) => `${count} running`,
  openProject: (name: string) => `Open ${name}`,
  newInProject: (name: string) => `New conversation in ${name}`,
  openContainer: (name: string) => `Open ${name}`,
  containerTooltip: (name: string, status: string) => `${name} · ${status}`,
  startContainer: (name: string) => `Start ${name}`,
  stopContainer: (name: string) => `Stop ${name}`,
} as const;
