export const CLI_LABELS = {
  name: "tesseract",
  usage: "usage: tesseract <command> [options]   (add --json for machine-readable output)",
  legacyUsage:
    "       tesseract --sync [--confidential] | --pull [--dry-run] [--force] | --revert [--force] | --sync-status | --gemini-key=KEY",
  commandsHeading: "Commands:",
  flagsHeading: "Flags (same as the desktop app):",
  globalHeading: "Global options:",
  globalFlags: [
    ["--json", "Print machine-readable JSON on stdout"],
    ["--verbose", "Print every log line of long operations"],
    ["--help", "Show help for a command"],
  ],
  commandHelp: (name: string) => `Run tesseract help ${name} for the options of ${name}.`,
  unknown: (arg: string) => `tesseract: unknown option or command: ${arg}`,
  unknownSubcommand: (command: string, arg: string) => `tesseract ${command}: unknown subcommand: ${arg}`,
  missingArgument: (command: string, what: string) => `tesseract ${command}: missing ${what}`,
  invalidValue: (flag: string, value: string) => `invalid value for --${flag}: ${value}`,
  failed: (message: string) => `tesseract: ${message}`,
  interrupted: "Interrupted",
  getOnHost: "tesseract --get runs inside the sandbox (in /workspace/projects/<id>); on this computer use tesseract --sync",
  help: {
    sync: "Copy the current directory to the sandbox and exit",
    confidential: "With --sync: send the project under a pseudonym and keep its name on this computer",
    pull: "Copy sandbox changes back into the current directory and exit",
    dryRun: "With --pull: show what would change, write nothing",
    force: "With --pull/--revert: overwrite files edited on the host",
    revert: "Undo the last --pull in the current directory and exit",
    syncStatus: "Show sandbox changes and sync-back snapshots and exit",
    get: "Runs inside the sandbox; on this computer use --sync",
    geminiKey: "Save the Gemini API key for voice notes on the sandbox and exit",
    version: "Print the version",
    help: "Show this help",
  },
  gemini: {
    usage: "tesseract --gemini-key=KEY",
    missingKey: "tesseract --gemini-key: missing the key, e.g. tesseract --gemini-key=AIza...",
    saved: (sandbox: string) => `Gemini API key saved on ${sandbox}`,
  },
  summary: {
    status: "Show the connection, Docker, sandbox and Android emulator at a glance",
    open: "Open the Tesseract app (or bring it to the front) on a page",
    doctor: "Check Docker, the sandbox image, hardware acceleration, the Android SDK and the tailnet",
    sandbox: "Manage the local sandbox stack: status, up, down, restart, logs, build, pair",
    server: "Run this computer as a headless Tesseract server: install, uninstall, status, pair",
    containers: "Manage server containers (systemd + Docker, own tailnet node): ls, create, start, stop, rm, ssh, build",
    domains: "Publish container ports on your own domains through Cloudflare Tunnel: ls, add, rm, zones, sync, login",
    android: "Manage the host Android emulator: images, install, avd create|list|start|delete",
    pair: "Print the pairing link and a QR code for the Tesseract phone app",
    sync: "Sync the current directory with the sandbox: push, pull, revert, status",
    config: "Read or change Tesseract settings: get, set, unset, path",
    version: "Print the version",
    help: "Show help for a command",
  },
  usageLines: {
    status: ["tesseract status [--json]"],
    open: ["tesseract open [overview|agents|projects|files|terminals|display|containers|domains]"],
    doctor: [
      "tesseract doctor [docker|image|kvm|sdk|tailnet]... [--json]",
      "",
      "tailnet is only checked when named: why the phone times out over Tailscale (tesseract doctor tailnet).",
    ],
    sandbox: [
      "tesseract sandbox status",
      "tesseract sandbox up",
      "tesseract sandbox down [--volumes]",
      "tesseract sandbox restart [service]",
      "tesseract sandbox logs [--tail N] [--follow]",
      "tesseract sandbox build [--with android,flutter,mono,whisper|all|none] [--pull | --existing] [--verbose]",
      "tesseract sandbox pair [--no-qr]",
    ],
    server: [
      "tesseract server install [--mode tailscale|host-tailscale|local] [--hostname NAME] [--tailnet-domain NAME.ts.net]",
      "                         [--authkey KEY] [--with android,flutter,mono,whisper|all|none] [--image REF] [--build]",
      "                         [--claude-token TOKEN] [--no-host-shell] [--host-https-port 8443] [--reset-tailscale] [--dry-run]",
      "tesseract server uninstall [--volumes]",
      "tesseract server status",
      "tesseract server pair [--no-qr]",
      "",
      "TS_AUTHKEY, TS_TAILNET_DOMAIN and CLAUDE_CODE_OAUTH_TOKEN are read when the matching option is missing.",
      "The auth key is only used on the sandbox's first login. To switch keys or tailnets, add --reset-tailscale:",
      "it deletes only the sandbox's tailscale volume (workspace and home stay) so the new key logs in.",
    ],
    containers: [
      "tesseract containers [ls]",
      "tesseract containers create <name> [--cpus N] [--memory MB]",
      "tesseract containers start|stop|restart|logs|ssh <name>",
      "tesseract containers rm <name> --yes",
      "tesseract containers build [--verbose]",
      "tesseract containers doctor",
      "tesseract containers tailscale-key [--tags tag:a,tag:b] [--clear]   (reads the key from stdin)",
      "",
      "Needs Docker with the sysbox-runc runtime. TESSERACT_SERVER_TS_AUTHKEY overrides the saved Tailscale key.",
    ],
    domains: [
      "tesseract domains [ls]",
      "tesseract domains add <hostname> <container> <port> [--https]",
      "tesseract domains rm <hostname|id>",
      "tesseract domains zones",
      "tesseract domains sync",
      "tesseract domains login   (reads a Cloudflare API token from stdin)",
      "tesseract domains logout",
      "",
      "Token permissions: Zone:Read, Zone:DNS:Edit, Account:Cloudflare Tunnel:Edit. TESSERACT_CLOUDFLARE_TOKEN overrides the saved token.",
    ],
    android: [
      "tesseract android images [--refresh] [--all]",
      "tesseract android install <api|package>... [--accept-licenses] [--sdk PATH]",
      "tesseract android avd list",
      "tesseract android avd create [name] [--image API|package] [--device pixel_5|pixel_8|medium_phone|pixel_tablet] [--storage GB] [--ram MB] [--cores N] [--default]",
      "tesseract android avd start [name] [--detach] [--headless] [--gpu MODE]",
      "tesseract android avd delete <name>",
    ],
    pair: ["tesseract pair [--no-qr]"],
    sync: [
      "tesseract sync [push] [--confidential]",
      "tesseract sync pull [--dry-run] [--force]",
      "tesseract sync revert [--force]",
      "tesseract sync status",
    ],
    config: [
      "tesseract config path",
      "tesseract config get [key] [--reveal]",
      "tesseract config set <key> <value> [--force]",
      "tesseract config unset <key>",
    ],
    version: ["tesseract version"],
    help: ["tesseract help [command]"],
  },
  status: {
    heading: (version: string) => `Tesseract ${version}`,
    configFile: "Config",
    onboarding: "Setup",
    onboardingDone: "complete",
    onboardingAt: (step: string) => `not finished (at ${step})`,
    connection: "Sandbox",
    notPaired: "not paired (run tesseract sandbox build or tesseract pair)",
    sealed: "paired (token stored by the app)",
    reachable: "reachable",
    unreachable: "unreachable",
    docker: "Docker",
    dockerReady: (kind: string, version: string) => `${kind} ${version}`.trim(),
    dockerNotReady: (detail: string) => `not ready: ${detail}`,
    stack: "Stack",
    stackNone: "not configured",
    stackLine: (project: string, image: string, mode: string) => `${project} · ${image} · ${mode}`,
    services: "Services",
    noServices: "no containers",
    android: "Android",
    avdNone: "no default emulator",
    androidLine: (sdkRoot: string, avd: string) => `${avd} · ${sdkRoot}`,
    unavailable: (message: string) => `unavailable: ${message}`,
  },
  dockerKinds: {
    engine: "Docker Engine",
    desktop: "Docker Desktop",
    rootless: "Docker (rootless)",
    podman: "Podman",
    colima: "Colima",
    orbstack: "OrbStack",
    unknown: "Docker",
  },
  open: {
    unknownPage: (page: string, pages: string) => `unknown page ${page}; expected one of ${pages}`,
    launched: (path: string) => `Opened Tesseract (${path})`,
    linked: (url: string) => `Asked the system to open ${url}`,
    notFound: "Tesseract is not installed here; install the desktop app or set TESSERACT_APP_PATH",
  },
  doctor: {
    sections: { docker: "Docker", image: "Sandbox image", kvm: "Hardware acceleration", sdk: "Android SDK", tailnet: "Tailnet" },
    unknownSection: (id: string, ids: string) => `unknown check ${id}; expected one of ${ids}`,
    failedSection: "Check failed",
    allGood: "Everything looks good.",
    problems: (count: number) => `${count} problem${count === 1 ? "" : "s"} found.`,
    stackMissing: "Sandbox not configured",
    stackMissingDetail: "Run tesseract sandbox build, or finish the setup wizard in the app",
    imageMissing: (image: string) => `${image} is not on this computer`,
    imageMissingDetail: "Run tesseract sandbox build (or --pull) to get it",
    imagePresent: (image: string) => image,
    imageDetail: (size: string, version: string | null, created: string) =>
      [size, version ? `version ${version}` : null, created ? `created ${created}` : null].filter(Boolean).join(" · "),
    containerTitle: "Sandbox container",
    containerMissing: "No sandbox container yet; run tesseract sandbox up",
    containerState: (name: string, state: string) => `${name} is ${state}`,
    sdkMissing: "No Android SDK found",
    sdkMissingDetail: "Run tesseract android install 36 to install the emulator and a system image",
    sdkFound: (path: string) => path,
    sdkDetail: (emulator: string | null, images: number, avds: number) =>
      [
        emulator ? `emulator ${emulator}` : "emulator not installed",
        `${images} system image${images === 1 ? "" : "s"}`,
        `${avds} AVD${avds === 1 ? "" : "s"}`,
      ].join(" · "),
    unsupported: "Android emulator",
  },
  tailnet: {
    unknown: "unknown",
    nothing: "nothing",
    node: (dns: string, ip: string, suffix: string) => `${dns || "?"} (${ip || "no IPv4"}) on ${suffix || "?"}`,
    noCli: "Tailscale CLI not found on this computer",
    noCliFix: "Install the Tailscale app; the host shell and these checks need it",
    host: "This computer's Tailscale",
    hostDown: (state: string) => `This computer's Tailscale is not connected (${state})`,
    hostDownFix: "Open the Tailscale app and sign in to the tailnet your phones use",
    hostCliFailed: "tailscale status failed on this computer",
    hostHealth: "This computer's Tailscale reports problems",
    noSidecar: "The sandbox's tailscale sidecar is not running",
    noSidecarFix: "Run tesseract sandbox up, or tesseract server status to see why it stopped",
    sidecar: "Sandbox sidecar",
    loggedOut: "The sandbox sidecar is logged out of the tailnet",
    loggedOutFix:
      "Its node was deleted or expired, and the saved login is never retried with a new key.\nFix: tesseract server install --authkey <new key> --reset-tailscale",
    needsApproval: "The sandbox sidecar waits for approval in the admin console",
    needsApprovalFix: (name: string) => `Approve ${name} under Machines in the admin console, or use a pre-approved key`,
    sidecarDown: (state: string) => `The sandbox sidecar is not on the tailnet (${state})`,
    wantsLogin: "The sidecar asks for an interactive login",
    noHttps: "No HTTPS certificate domain: https://<sandbox> cannot answer",
    noHttpsFix: (suffix: string) => `Admin console of ${suffix || "that tailnet"} → DNS → enable MagicDNS and HTTPS Certificates`,
    keyExpiry: "Node key expiry",
    keyExpiryDetail: (when: string) => `${when}; the sandbox drops off the tailnet then unless key expiry is disabled for it`,
    sidecarHealth: "The sidecar reports problems",
    logErrors: "Auth errors in the sidecar log",
    sameTailnet: (suffix: string) => `This computer and the sandbox are both on ${suffix}`,
    splitTailnet: (host: string, sidecar: string) => `This computer is on ${host}, the sandbox on ${sidecar}`,
    splitTailnetFix: (host: string) =>
      `The sandbox still uses the old key's identity, so phones on one tailnet cannot reach it.\nFix: tesseract server install --authkey <key from ${host}> --reset-tailscale`,
    staleDomain: (env: string, actual: string) => `TS_TAILNET_DOMAIN is ${env}, but the sandbox is on ${actual}`,
    staleDomainFix: (actual: string) => `The pairing link names a host that does not exist.\nFix: tesseract server install --tailnet-domain ${actual}, then scan the new QR code`,
    staleUrl: (advertised: string, actual: string) => `The sandbox advertises ${advertised}, but answers at ${actual}`,
    staleUrlFix: "Phones paired with the old link time out.\nFix: tesseract server install, then scan the new QR code",
    renamedFix: (name: string) =>
      `An old ${name} node still exists in the tailnet, so the new one got another name and phones dial the old one.\nFix: delete the old ${name} machines in the admin console, then tesseract sandbox restart and tesseract server pair`,
    urlMatches: "The pairing URL is the sandbox's real name",
    keyIgnored: (volume: string) => `A saved TS_AUTHKEY is unused: the sandbox kept its old identity in ${volume}`,
    keyIgnoredFix: "The key switch never happened.\nFix: tesseract server install --authkey <new key> --reset-tailscale",
    identity: (volume: string) => `Sandbox identity in ${volume}`,
    identityDetail: (created: string | null) =>
      `created ${created ?? "?"}; a new auth key only takes effect with tesseract server install --reset-tailscale`,
    peerMissing: (ip: string) => `This computer does not see the sandbox (${ip}) as a peer`,
    peerMissingFix: "Different tailnets, or an ACL that hides it: check the grants allow your devices → tag:tesseract tcp:443",
    peerVisible: "This computer sees the sandbox as a peer",
    stalePeers: "Other sandbox nodes in the tailnet (old identities?)",
    peerLine: (dns: string, ip: string, online: boolean, seen: string) => `${dns} ${ip} ${online ? "online" : `offline, last seen ${seen || "?"}`}`,
    stalePeersFix: "Remove them under Machines in the admin console, then re-pair: tesseract server pair",
    ping: "tailscale ping",
    pingFailed: "tailscale ping to the sandbox fails",
    pingRelayed: "tailscale ping goes through a DERP relay (no direct connection); slower, but it works",
    pingFix: "Fix: tesseract sandbox restart; if it persists, tesseract server install --authkey <key> --reset-tailscale",
    controllerUp: "The controller answers inside the sandbox",
    controllerDown: "The controller does not answer inside the sandbox",
    controllerDownFix: "Every request times out regardless of Tailscale. See: tesseract sandbox logs --tail 200",
    noServe: "tailscale serve in the sidecar does not proxy to the controller",
    noServeFix: "Fix: tesseract sandbox restart",
    splitNetwork: "The sidecar cannot reach the controller, although it runs: they no longer share a network",
    splitNetworkFix:
      "Happens when only the tailscale container was restarted; the sandbox kept the old network.\nFix: tesseract sandbox restart (restarts both, sidecar first)",
    healthOk: "HTTPS /v1/health answers over the tailnet",
    healthFailed: (code: string) => `HTTPS /v1/health over the tailnet fails (${code === "000" ? "timeout or no connection" : code})`,
    dnsMismatch: (name: string, got: string, want: string) => `${name} resolves to ${got} here, not ${want}`,
    dnsFix: "Turn on MagicDNS and 'Use Tailscale DNS settings', or flush the DNS cache",
    staleServe: (front: string, target: string, ip: string) => `https://${front} → ${target}, but this computer's Tailscale IP is now ${ip}`,
    staleServeFix: (restart: string) => `The host shell still uses the old IP.\nFix: ${restart}, then tesseract server install`,
    hostShell: "Host shell",
    hostShellHttpsOk: "The host shell's HTTPS front answers (what the phone uses)",
    hostShellHttpsFailed: (code: string) => `The host shell's HTTPS front fails (${code === "000" ? "timeout or no connection" : code}); the phone cannot pair`,
    hostShellHttpsFix:
      "tailscale serve or its certificate is broken: check tailscale serve status, that HTTPS Certificates are on for the tailnet, then tesseract server install to re-create the front",
    hostShellDown: (target: string) => `The host shell does not answer on ${target}`,
    hostShellDownFix: (restart: string) => `Fix: ${restart}`,
    modeDrift: (mode: string) => `The config says mode ${mode}, but a tailscale sidecar stack is running`,
    modeDriftFix: "The running stack was started with another config. Checking the running one; tesseract sandbox up recreates it from the config",
    otherMode: (mode: string) => `Mode ${mode}: no sandbox sidecar to check`,
  },
  containers: {
    nameArg: "container name",
    none: "No server containers. Create one with tesseract containers create <name>",
    header: ["NAME", "STATE", "TAILNET", "TUNNEL", "LIMITS"],
    fields: { name: "Name", state: "State", tailnet: "Tailnet", ssh: "SSH", tunnel: "Tunnel" },
    notJoined: "not joined",
    checkMark: { ok: "✓", warning: "!", error: "✗", pending: "…" },
    building: "Building the server image…",
    creating: (name: string) => `Creating ${name}…`,
    confirmRemove: (name: string) => `This deletes ${name}, its data and its public URLs. Re-run with --yes to confirm.`,
    removed: (name: string) => `Removed ${name}`,
    noTailnet: (name: string) => `${name} hasn't joined the tailnet; add a key with tesseract containers tailscale-key, or run tailscale up --ssh inside it`,
    keyFromStdin: "Pipe the auth key on stdin, e.g. tesseract containers tailscale-key < key.txt",
  },
  domains: {
    none: "No public URLs. Add one with tesseract domains add <hostname> <container> <port>",
    header: ["URL", "TARGET", "SCHEME", "STATUS"],
    noZones: "No Cloudflare zones (run tesseract domains login)",
    hostnameArg: "hostname",
    addUsage: "usage: tesseract domains add <hostname> <container> <port> [--https]",
    adding: (hostname: string, container: string, port: number) => `Routing https://${hostname} to ${container}:${port}…`,
    added: (hostname: string) => `https://${hostname} is live`,
    removed: (hostname: string) => `Removed https://${hostname}`,
    notFound: (target: string) => `No public URL ${target}`,
    tokenFromStdin: "Pipe the Cloudflare API token on stdin, e.g. tesseract domains login < token.txt",
  },
  sandbox: {
    noContext:
      "Could not find the sandbox build files (infra/compose); reinstall Tesseract, run this from the repository, or set TESSERACT_SANDBOX_CONTEXT",
    noServices: "No sandbox containers",
    header: ["SERVICE", "CONTAINER", "STATE", "HEALTH"],
    up: "Starting the sandbox…",
    down: "Stopping the sandbox…",
    restart: "Restarting the sandbox…",
    unknownComponent: (name: string, valid: string) => `unknown component ${name}; expected ${valid}, all or none`,
    baseIncluded: (name: string) => `${name} is part of the base image; nothing to add`,
    configured: (file: string) => `Saved the sandbox settings to ${file}`,
    phase: {
      idle: "Idle",
      preflight: "Checking Docker and disk space…",
      building: (percent: string, step: string) => ["Building", percent, step].filter(Boolean).join(" "),
      pulling: (percent: string, detail: string) => ["Pulling", percent, detail].filter(Boolean).join(" "),
      starting: "Starting the containers…",
      waiting: "Waiting for the controller to answer…",
      pairing: "Pairing…",
      done: (url: string) => `Sandbox ready at ${url}`,
      failed: (phase: string, message: string) => `${phase} failed: ${message}`,
      cancelled: "Cancelled",
    },
  },
  server: {
    dockerNotReady: (detail: string) => `Docker is not ready: ${detail}`,
    invalidMode: (value: string, modes: string) => `unknown mode ${value}; expected ${modes}`,
    invalidPort: (value: string) => `--host-https-port needs a port number, got ${value}`,
    noTailscale: "The tailscale command was not found; install Tailscale or put it on PATH",
    noTailscaleIp: "Tailscale has no IPv4 address on this computer; run tailscale up first",
    noController: (path: string, variable: string) =>
      `tesseract-controller was not found next to ${path}; keep both binaries in one directory or set ${variable}`,
    dryRun: "Dry run: nothing was changed.",
    plannedEnv: (file: string) => `Sandbox settings (${file}):`,
    plannedImage: (mode: string, image: string) => `Image: ${mode} ${image}`,
    plannedService: (kind: string, file: string) => `Host shell service (${kind}): ${file}`,
    plannedCommand: (command: string) => `  $ ${command}`,
    skippedHostShell: "Host shell: skipped (--no-host-shell)",
    writing: (file: string) => `Writing ${file}`,
    serviceStarted: (kind: string) => `Started the host shell service (${kind})`,
    serviceRemoved: (file: string) => `Removed ${file}`,
    authKeyIgnored: (volume: string) =>
      `Note: the sandbox already has a tailnet identity in ${volume}, so this auth key is ignored. Add --reset-tailscale to switch to it.`,
    resetNeedsKey: "--reset-tailscale needs a new auth key (--authkey or TS_AUTHKEY)",
    resetNeedsMode: "--reset-tailscale only applies to --mode tailscale",
    resettingTailscale: (volume: string) => `Removing ${volume} so the sandbox logs in with the new key (workspace and home stay)`,
    serveAdded: (port: number) => `Tailscale serves the host shell on HTTPS port ${port}`,
    serveRemoved: (port: number) => `Stopped serving HTTPS port ${port}`,
    hostShellReady: (url: string) => `Host shell answers at ${url}`,
    hostShellNotReady: (url: string, logs: string) => `The host shell did not answer at ${url}; check ${logs}`,
    commandFailed: (command: string, detail: string) => `${command} failed: ${detail}`,
    linger: (user: string) => `To keep the host shell running after you log out, run: sudo loginctl enable-linger ${user}`,
    autoLogin: "LaunchAgents run while you are logged in; turn on automatic login and keep the Mac awake (sudo pmset -a sleep 0)",
    nextSteps: "Next steps:",
    setPin: (command: string) => `  1. Set the host shell PIN: ${command} host pin`,
    pairSteps: "  Pair the phone with both QR codes: tesseract server pair",
    sandboxHeading: "Sandbox",
    hostHeading: "Host shell",
    hostPairFailed: (detail: string) => `Could not read the host shell pairing: ${detail}`,
    hostScan: "Scan with the phone app (Host shell), or open the link on the phone. The PIN unlocks it.",
    pinMissing: (command: string) => `No PIN is set yet; run ${command} host pin`,
    statusRows: {
      stack: "Stack",
      service: "Host shell service",
      serve: "Tailscale serve",
      sandboxHealth: "Sandbox health",
      hostHealth: "Host shell health",
    },
    running: "running",
    stopped: "not running",
    notInstalled: "not installed",
    healthy: (url: string) => `ok (${url})`,
    unhealthy: (url: string) => `no answer (${url})`,
    unknown: "unknown",
  },
  android: {
    noImages: "No system images for this computer",
    imagesHeader: ["API", "VERSION", "ABI", "SIZE", "INSTALLED", "PACKAGE"],
    toolsHeader: ["PACKAGE", "REVISION", "SIZE", "INSTALLED"],
    installedYes: (revision: string) => revision,
    installedNo: "-",
    sdkRoot: (path: string) => `SDK: ${path}`,
    licensesNeeded: (ids: string) => `These packages need license acceptance: ${ids}`,
    licensesHint: "Read the licenses above, then re-run with --accept-licenses",
    licenseHeading: (id: string) => `--- License ${id} ---`,
    licenseRequired: "License not accepted",
    nothingToInstall: "Nothing to install",
    installed: (count: number, sdkRoot: string) => `Installed ${count} package${count === 1 ? "" : "s"} into ${sdkRoot}`,
    progress: (index: number, count: number, pkg: string, stage: string, amount: string, rate: string) =>
      `[${index}/${count}] ${pkg} ${stage} ${amount}${rate ? ` ${rate}` : ""}`,
    rate: (perSecond: string) => `${perSecond}/s`,
    unknownToken: (token: string) => `unknown package or API level: ${token}`,
    noAvds: "No AVDs yet; run tesseract android avd create",
    avdHeader: ["", "NAME", "TARGET", "ABI", "PATH"],
    defaultMark: "*",
    imageNotInstalled: (path: string, api: number) => `${path} is not installed; run tesseract android install ${api}`,
    invalidImage: (value: string) => `not a system image: ${value}`,
    created: (name: string, path: string) => `Created ${name} in ${path}`,
    deleted: (name: string) => `Deleted ${name}`,
    noAvdToStart: "No AVD to start; run tesseract android avd create first",
    starting: (avd: string) => `Starting ${avd}…`,
    detached: (avd: string, serial: string) => `Started ${avd} as ${serial}`,
    running: (avd: string, serial: string) => `${avd} is running as ${serial}; press Ctrl+C to stop it`,
    stopped: "Emulator stopped",
    noPort: "No free emulator console port",
    emulatorMissing: (sdkRoot: string) => `The emulator is not installed in ${sdkRoot}; run tesseract android install emulator`,
    invalidNumber: (flag: string) => `--${flag} needs a positive number`,
  },
  pair: {
    heading: (name: string | null) => (name ? `Pair a phone with ${name}` : "Pair a phone with this sandbox"),
    scan: "Scan the code with the Tesseract phone app, or open the link on the phone.",
    local: "This address only works on this computer. Use Tailscale mode to pair a phone.",
    sealed: (error: string, urlVar: string, tokenVar: string) =>
      `the app keeps the sandbox token in the system keychain, which this command cannot read, and no local sandbox was found (${error}). Open the app's Pair dialog, or set ${urlVar} and ${tokenVar}`,
  },
  config: {
    missingKey: (key: string) => `${key} is not set`,
    unknownKey: (key: string, keys: string) => `unknown key ${key}; known keys: ${keys} (use --force to write it anyway)`,
    readOnlyKey: (key: string) => `${key} can't be set from the command line; use tesseract pair or the app's settings`,
    invalid: (key: string, expected: string) => `invalid value for ${key}; expected ${expected}`,
    saved: (key: string) => `Saved ${key}`,
    removed: (key: string) => `Removed ${key}`,
    expected: {
      appearance: "system, light or dark",
      zoom: "a number between 0.67 and 2",
      sidebarWidth: "a number of pixels",
      boolean: "true or false",
      path: "an absolute path",
      text: "a non-empty value",
      avd: "an AVD name (letters, digits, . _ -)",
      link: "a pairing link",
      url: "an http(s) URL",
    },
  },
  version: (name: string, version: string) => `${name} ${version}`,
} as const;
