export const CLI_LABELS = {
  name: "monolith",
  usage: "usage: monolith <command> [options]   (add --json for machine-readable output)",
  legacyUsage: "       monolith --sync [--confidential] | --pull [--dry-run] [--force] | --revert [--force] | --sync-status",
  commandsHeading: "Commands:",
  flagsHeading: "Sync flags (same as the desktop app):",
  globalHeading: "Global options:",
  globalFlags: [
    ["--json", "Print machine-readable JSON on stdout"],
    ["--verbose", "Print every log line of long operations"],
    ["--help", "Show help for a command"],
  ],
  commandHelp: (name: string) => `Run monolith help ${name} for the options of ${name}.`,
  unknown: (arg: string) => `monolith: unknown option or command: ${arg}`,
  unknownSubcommand: (command: string, arg: string) => `monolith ${command}: unknown subcommand: ${arg}`,
  missingArgument: (command: string, what: string) => `monolith ${command}: missing ${what}`,
  invalidValue: (flag: string, value: string) => `invalid value for --${flag}: ${value}`,
  failed: (message: string) => `monolith: ${message}`,
  interrupted: "Interrupted",
  getOnHost: "monolith --get runs inside the sandbox (in /workspace/projects/<id>); on this computer use monolith --sync",
  help: {
    sync: "Copy the current directory to the sandbox and exit",
    confidential: "With --sync: send the project under a pseudonym and keep its name on this computer",
    pull: "Copy sandbox changes back into the current directory and exit",
    dryRun: "With --pull: show what would change, write nothing",
    force: "With --pull/--revert: overwrite files edited on the host",
    revert: "Undo the last --pull in the current directory and exit",
    syncStatus: "Show sandbox changes and sync-back snapshots and exit",
    get: "Runs inside the sandbox; on this computer use --sync",
    version: "Print the version",
    help: "Show this help",
  },
  summary: {
    status: "Show the connection, Docker, sandbox and Android emulator at a glance",
    open: "Open the Monolith app (or bring it to the front) on a page",
    doctor: "Check Docker, the sandbox image, hardware acceleration and the Android SDK",
    sandbox: "Manage the local sandbox stack: status, up, down, restart, logs, build, pair",
    android: "Manage the host Android emulator: images, install, avd create|list|start|delete",
    pair: "Print the pairing link and a QR code for the Monolith phone app",
    sync: "Sync the current directory with the sandbox: push, pull, revert, status",
    config: "Read or change Monolith settings: get, set, unset, path",
    version: "Print the version",
    help: "Show help for a command",
  },
  usageLines: {
    status: ["monolith status [--json]"],
    open: ["monolith open [overview|agents|projects|files|terminals|display]"],
    doctor: ["monolith doctor [docker|image|kvm|sdk]... [--json]"],
    sandbox: [
      "monolith sandbox status",
      "monolith sandbox up",
      "monolith sandbox down [--volumes]",
      "monolith sandbox restart [service]",
      "monolith sandbox logs [--tail N] [--follow]",
      "monolith sandbox build [--with android,flutter,mono,whisper|all|none] [--pull | --existing] [--verbose]",
      "monolith sandbox pair [--no-qr]",
    ],
    android: [
      "monolith android images [--refresh] [--all]",
      "monolith android install <api|package>... [--accept-licenses] [--sdk PATH]",
      "monolith android avd list",
      "monolith android avd create [name] [--image API|package] [--device pixel_5|pixel_8|medium_phone|pixel_tablet] [--storage GB] [--ram MB] [--cores N] [--default]",
      "monolith android avd start [name] [--detach] [--headless] [--gpu MODE]",
      "monolith android avd delete <name>",
    ],
    pair: ["monolith pair [--no-qr]"],
    sync: [
      "monolith sync [push] [--confidential]",
      "monolith sync pull [--dry-run] [--force]",
      "monolith sync revert [--force]",
      "monolith sync status",
    ],
    config: [
      "monolith config path",
      "monolith config get [key] [--reveal]",
      "monolith config set <key> <value> [--force]",
      "monolith config unset <key>",
    ],
    version: ["monolith version"],
    help: ["monolith help [command]"],
  },
  status: {
    heading: (version: string) => `Monolith ${version}`,
    configFile: "Config",
    onboarding: "Setup",
    onboardingDone: "complete",
    onboardingAt: (step: string) => `not finished (at ${step})`,
    connection: "Sandbox",
    notPaired: "not paired (run monolith sandbox build or monolith pair)",
    sealed: "paired (token stored by the app)",
    reachable: "reachable",
    unreachable: "unreachable",
    docker: "Docker",
    dockerReady: (kind: string, version: string) => `${kind} ${version}`.trim(),
    dockerNotReady: (detail: string) => `not ready: ${detail}`,
    stack: "Stack",
    stackNone: "not configured",
    stackLine: (project: string, image: string, mode: string) => `${project} · ${image} · ${mode}`,
    services: "Services",
    noServices: "no containers",
    android: "Android",
    avdNone: "no default emulator",
    androidLine: (sdkRoot: string, avd: string) => `${avd} · ${sdkRoot}`,
    unavailable: (message: string) => `unavailable: ${message}`,
  },
  dockerKinds: {
    engine: "Docker Engine",
    desktop: "Docker Desktop",
    rootless: "Docker (rootless)",
    podman: "Podman",
    colima: "Colima",
    orbstack: "OrbStack",
    unknown: "Docker",
  },
  open: {
    unknownPage: (page: string, pages: string) => `unknown page ${page}; expected one of ${pages}`,
    launched: (path: string) => `Opened Monolith (${path})`,
    linked: (url: string) => `Asked the system to open ${url}`,
    notFound: "Monolith is not installed here; install the desktop app or set MONOLITH_APP_PATH",
  },
  doctor: {
    sections: { docker: "Docker", image: "Sandbox image", kvm: "Hardware acceleration", sdk: "Android SDK" },
    unknownSection: (id: string, ids: string) => `unknown check ${id}; expected one of ${ids}`,
    failedSection: "Check failed",
    allGood: "Everything looks good.",
    problems: (count: number) => `${count} problem${count === 1 ? "" : "s"} found.`,
    stackMissing: "Sandbox not configured",
    stackMissingDetail: "Run monolith sandbox build, or finish the setup wizard in the app",
    imageMissing: (image: string) => `${image} is not on this computer`,
    imageMissingDetail: "Run monolith sandbox build (or --pull) to get it",
    imagePresent: (image: string) => image,
    imageDetail: (size: string, version: string | null, created: string) =>
      [size, version ? `version ${version}` : null, created ? `created ${created}` : null].filter(Boolean).join(" · "),
    containerTitle: "Sandbox container",
    containerMissing: "No sandbox container yet; run monolith sandbox up",
    containerState: (name: string, state: string) => `${name} is ${state}`,
    sdkMissing: "No Android SDK found",
    sdkMissingDetail: "Run monolith android install 36 to install the emulator and a system image",
    sdkFound: (path: string) => path,
    sdkDetail: (emulator: string | null, images: number, avds: number) =>
      [
        emulator ? `emulator ${emulator}` : "emulator not installed",
        `${images} system image${images === 1 ? "" : "s"}`,
        `${avds} AVD${avds === 1 ? "" : "s"}`,
      ].join(" · "),
    unsupported: "Android emulator",
  },
  sandbox: {
    noContext:
      "Could not find the sandbox build files (infra/compose); reinstall Monolith, run this from the repository, or set MONOLITH_SANDBOX_CONTEXT",
    noServices: "No sandbox containers",
    header: ["SERVICE", "CONTAINER", "STATE", "HEALTH"],
    up: "Starting the sandbox…",
    down: "Stopping the sandbox…",
    restart: "Restarting the sandbox…",
    unknownComponent: (name: string, valid: string) => `unknown component ${name}; expected ${valid}, all or none`,
    baseIncluded: (name: string) => `${name} is part of the base image; nothing to add`,
    configured: (file: string) => `Saved the sandbox settings to ${file}`,
    phase: {
      idle: "Idle",
      preflight: "Checking Docker and disk space…",
      building: (percent: string, step: string) => ["Building", percent, step].filter(Boolean).join(" "),
      pulling: (percent: string, detail: string) => ["Pulling", percent, detail].filter(Boolean).join(" "),
      starting: "Starting the containers…",
      waiting: "Waiting for the controller to answer…",
      pairing: "Pairing…",
      done: (url: string) => `Sandbox ready at ${url}`,
      failed: (phase: string, message: string) => `${phase} failed: ${message}`,
      cancelled: "Cancelled",
    },
  },
  android: {
    noImages: "No system images for this computer",
    imagesHeader: ["API", "VERSION", "ABI", "SIZE", "INSTALLED", "PACKAGE"],
    toolsHeader: ["PACKAGE", "REVISION", "SIZE", "INSTALLED"],
    installedYes: (revision: string) => revision,
    installedNo: "-",
    sdkRoot: (path: string) => `SDK: ${path}`,
    licensesNeeded: (ids: string) => `These packages need license acceptance: ${ids}`,
    licensesHint: "Read the licenses above, then re-run with --accept-licenses",
    licenseHeading: (id: string) => `--- License ${id} ---`,
    licenseRequired: "License not accepted",
    nothingToInstall: "Nothing to install",
    installed: (count: number, sdkRoot: string) => `Installed ${count} package${count === 1 ? "" : "s"} into ${sdkRoot}`,
    progress: (index: number, count: number, pkg: string, stage: string, amount: string, rate: string) =>
      `[${index}/${count}] ${pkg} ${stage} ${amount}${rate ? ` ${rate}` : ""}`,
    rate: (perSecond: string) => `${perSecond}/s`,
    unknownToken: (token: string) => `unknown package or API level: ${token}`,
    noAvds: "No AVDs yet; run monolith android avd create",
    avdHeader: ["", "NAME", "TARGET", "ABI", "PATH"],
    defaultMark: "*",
    imageNotInstalled: (path: string, api: number) => `${path} is not installed; run monolith android install ${api}`,
    invalidImage: (value: string) => `not a system image: ${value}`,
    created: (name: string, path: string) => `Created ${name} in ${path}`,
    deleted: (name: string) => `Deleted ${name}`,
    noAvdToStart: "No AVD to start; run monolith android avd create first",
    starting: (avd: string) => `Starting ${avd}…`,
    detached: (avd: string, serial: string) => `Started ${avd} as ${serial}`,
    running: (avd: string, serial: string) => `${avd} is running as ${serial}; press Ctrl+C to stop it`,
    stopped: "Emulator stopped",
    noPort: "No free emulator console port",
    emulatorMissing: (sdkRoot: string) => `The emulator is not installed in ${sdkRoot}; run monolith android install emulator`,
    invalidNumber: (flag: string) => `--${flag} needs a positive number`,
  },
  pair: {
    heading: (name: string | null) => (name ? `Pair a phone with ${name}` : "Pair a phone with this sandbox"),
    scan: "Scan the code with the Monolith phone app, or open the link on the phone.",
    local: "This address only works on this computer. Use Tailscale mode to pair a phone.",
    sealed: (error: string, urlVar: string, tokenVar: string) =>
      `the app keeps the sandbox token in the system keychain, which this command cannot read, and no local sandbox was found (${error}). Open the app's Pair dialog, or set ${urlVar} and ${tokenVar}`,
  },
  config: {
    missingKey: (key: string) => `${key} is not set`,
    unknownKey: (key: string, keys: string) => `unknown key ${key}; known keys: ${keys} (use --force to write it anyway)`,
    readOnlyKey: (key: string) => `${key} can't be set from the command line; use monolith pair or the app's settings`,
    invalid: (key: string, expected: string) => `invalid value for ${key}; expected ${expected}`,
    saved: (key: string) => `Saved ${key}`,
    removed: (key: string) => `Removed ${key}`,
    expected: {
      appearance: "system, light or dark",
      zoom: "a number between 0.67 and 2",
      sidebarWidth: "a number of pixels",
      boolean: "true or false",
      path: "an absolute path",
      text: "a non-empty value",
      avd: "an AVD name (letters, digits, . _ -)",
      link: "a pairing link",
      url: "an http(s) URL",
    },
  },
  version: (name: string, version: string) => `${name} ${version}`,
} as const;
