export const PROCESSES_LABELS = {
  ports: "Listening ports",
  portsSubtitle: "Servers started from this project",
  open: "Open in browser",
  copy: "Copy URL",
  copied: "URL copied",
  noUrl: "No address reachable from this machine",
  port: (port: number) => `:${port}`,
  scripts: "Scripts",
  scriptsSubtitle: (pm: string) => `Package scripts run with ${pm}`,
  run: "Run",
  runDisplay: "Run on display",
  list: "Processes",
  listEmpty: "Nothing has run in this project yet.",
  newCommand: "Run command",
  stop: "Stop",
  showLogs: "Show logs",
  hideLogs: "Hide logs",
  metaRunning: (when: string) => `started ${when}`,
  metaEnded: (duration: string, when: string) => `ran ${duration} · ended ${when}`,
  exit: (code: number) => `exit ${code}`,
  pid: (pid: number) => `pid ${pid}`,
  display: "display",
  logsTitle: (name: string) => `Logs · ${name}`,
  stopTitle: (name: string) => `Stop ${name}?`,
  stopBody: "The process gets SIGTERM, then SIGKILL after 5 seconds.",
  stopConfirm: "Stop",
  cancel: "Cancel",
  stopped: (name: string) => `Stopped ${name}`,
  started: (name: string) => `Started ${name}`,
  states: {
    starting: "Starting",
    running: "Running",
    exited: "Exited",
    failed: "Failed",
    stopped: "Stopped",
    orphaned: "Orphaned",
  },
} as const;
